/**
 * AUTO-GENERATED — do not edit.
 *
 * Written by `yarn generate:ownership` from
 * packages/core/manifests/component-ownership.manifest.json.
 * `yarn validate:ownership` fails if this file drifts from it.
 *
 * A narrowing of the ownership manifest to the field the docs render: the
 * declared styling surface (ADR-19). Components absent from this table have not
 * declared one yet, and the count is ratcheted in
 * packages/tooling/src/ownership/unclassified-ceiling.json.
 */

/** One component's declared styling surface, as the docs render it. */
export interface DocAnatomy {
  readonly parts: readonly string[] | 'none'
  readonly states: readonly string[]
  readonly componentTokens: readonly string[]
  readonly riskTier: 'A' | 'B' | 'C' | 'D'
  readonly recipes?: readonly string[]
  readonly optionalParts?: readonly string[]
  readonly globalDefaults?: readonly string[]
  /** RTL contract (TASK-OSS-P4-05). */
  readonly rtl?: {
    readonly mirrors: 'layout' | 'none'
    readonly keyboard: 'swap-horizontal' | 'none'
    readonly icons?: readonly string[]
  }
}

/** Public components in the catalog, declared or not. */
export const PUBLIC_COMPONENT_COUNT = 144

/** Components that have declared an anatomy, by exported name. */
export const ANATOMY: Readonly<Record<string, DocAnatomy>> = {
  DzAccordion: {
    parts: ['root', 'item', 'trigger', 'indicator', 'content'],
    states: ['ready', 'disabled', 'open', 'closed'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size', 'variant'],
    optionalParts: ['item', 'trigger', 'indicator', 'content'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['indicator'] },
  },
  DzAnchor: {
    parts: ['root', 'list', 'item'],
    states: ['ready', 'active'],
    componentTokens: ['--dz-anchor-color', '--dz-anchor-hover-color', '--dz-anchor-active-color', '--dz-anchor-rail-color', '--dz-anchor-font-size', '--dz-anchor-item-gap', '--dz-anchor-indent'],
    riskTier: 'B',
    optionalParts: ['list', 'item'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzBackTop: {
    parts: ['root', 'icon'],
    states: ['idle'],
    componentTokens: ['--dz-back-top-offset', '--dz-back-top-z', '--dz-back-top-transition'],
    riskTier: 'B',
    recipes: ['size', 'variant', 'tone'],
    optionalParts: ['icon'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzBlockUI: {
    parts: ['root', 'content', 'overlay', 'description'],
    states: ['blocked', 'full-screen'],
    componentTokens: ['--dz-blockui-mask', '--dz-blockui-blur', '--dz-blockui-radius', '--dz-blockui-gap', '--dz-blockui-z', '--dz-blockui-message-color'],
    riskTier: 'B',
    optionalParts: ['overlay', 'description'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzBlockquote: {
    parts: ['root', 'content', 'footer'],
    states: [],
    componentTokens: [],
    riskTier: 'A',
    optionalParts: ['footer'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzBreadcrumb: {
    parts: ['root', 'list', 'item', 'item-label', 'separator'],
    states: ['ready', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    optionalParts: ['item', 'item-label', 'separator'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['separator'] },
  },
  DzButton: {
    parts: ['root', 'spinner'],
    states: ['idle', 'loading', 'disabled'],
    componentTokens: ['--dz-button-disabled-opacity', '--dz-button-focus-ring-color', '--dz-button-focus-ring-offset', '--dz-button-focus-ring-width', '--dz-button-font-family', '--dz-button-font-weight', '--dz-button-icon-font-size', '--dz-button-icon-height', '--dz-button-icon-width', '--dz-button-lg-font-size', '--dz-button-lg-gap', '--dz-button-lg-height', '--dz-button-lg-padding-x', '--dz-button-md-font-size', '--dz-button-md-gap', '--dz-button-md-height', '--dz-button-md-padding-x', '--dz-button-radius', '--dz-button-sm-font-size', '--dz-button-sm-gap', '--dz-button-sm-height', '--dz-button-sm-padding-x', '--dz-button-transition', '--dz-button-xl-font-size', '--dz-button-xl-gap', '--dz-button-xl-height', '--dz-button-xl-padding-x', '--dz-button-xs-font-size', '--dz-button-xs-gap', '--dz-button-xs-height', '--dz-button-xs-padding-x'],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['spinner'],
    globalDefaults: ['size', 'variant', 'tone'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzButtonGroup: {
    parts: ['root'],
    states: ['idle', 'disabled'],
    componentTokens: [],
    riskTier: 'A',
    recipes: ['variant', 'size', 'tone', 'orientation'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzCalendar: {
    parts: ['root', 'header', 'title', 'group', 'action', 'content', 'row', 'cell', 'item'],
    states: ['disabled', 'selected', 'today', 'in-range', 'outside-month'],
    componentTokens: ['--dz-calendar-cell-size', '--dz-calendar-cell-radius', '--dz-calendar-cell-foreground', '--dz-calendar-cell-hover-bg', '--dz-calendar-selected-bg', '--dz-calendar-selected-foreground', '--dz-calendar-range-bg', '--dz-calendar-today-ring', '--dz-calendar-header-foreground', '--dz-calendar-weekday-foreground', '--dz-calendar-outside-foreground', '--dz-calendar-outside-opacity', '--dz-calendar-disabled-opacity'],
    riskTier: 'C',
    recipes: ['size'],
    optionalParts: ['action', 'row', 'cell', 'item'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['action'] },
  },
  DzCaption: {
    parts: ['root'],
    states: [],
    componentTokens: [],
    riskTier: 'A',
    recipes: ['tone'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzCard: {
    parts: ['root', 'header', 'body', 'footer', 'action'],
    states: ['interactive', 'static'],
    componentTokens: ['--dz-card-radius', '--dz-card-padding', '--dz-card', '--dz-card-foreground', '--dz-card-border-color'],
    riskTier: 'B',
    recipes: ['variant'],
    optionalParts: ['header', 'body', 'footer', 'action'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzCarousel: {
    parts: ['root', 'viewport', 'content', 'item', 'list', 'item-indicator', 'action'],
    states: ['ready', 'empty', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['orientation'],
    optionalParts: ['item', 'list', 'item-indicator', 'action'],
    rtl: { mirrors: 'none', keyboard: 'swap-horizontal' },
  },
  DzCascader: {
    parts: ['root', 'trigger', 'label', 'clear', 'icon', 'content', 'panel', 'input', 'list', 'group', 'item', 'item-label', 'item-indicator', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    states: ['disabled', 'invalid', 'readonly', 'required', 'loading', 'open', 'closed', 'selected', 'active'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['clear', 'content', 'panel', 'input', 'list', 'group', 'item', 'item-label', 'item-indicator', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['icon', 'item-indicator'] },
  },
  DzCheckbox: {
    parts: ['root', 'control', 'indicator', 'label'],
    states: ['checked', 'unchecked', 'indeterminate', 'disabled', 'required'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['indicator', 'label'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzCheckboxGroup: {
    parts: ['root'],
    states: ['ready', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['orientation'],
    optionalParts: [],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzChip: {
    parts: ['root', 'close'],
    states: ['idle', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size', 'variant', 'tone'],
    optionalParts: ['close'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzCode: {
    parts: ['root'],
    states: [],
    componentTokens: [],
    riskTier: 'A',
    recipes: ['variant'],
    rtl: { mirrors: 'none', keyboard: 'none' },
  },
  DzCodeBlock: {
    parts: ['root', 'header', 'filename', 'language', 'copy-button', 'content', 'line-number'],
    states: [],
    componentTokens: [],
    riskTier: 'A',
    optionalParts: ['header', 'filename', 'language', 'copy-button', 'line-number'],
    rtl: { mirrors: 'none', keyboard: 'none' },
  },
  DzCollapse: {
    parts: ['root'],
    states: ['open', 'closed'],
    componentTokens: [],
    riskTier: 'B',
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzColorModeToggle: {
    parts: ['root'],
    states: [],
    componentTokens: ['--dz-color-mode-toggle-icon-size', '--dz-color-mode-toggle-transition'],
    riskTier: 'B',
    recipes: ['variant', 'size'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzColorPicker: {
    parts: ['root', 'trigger', 'indicator', 'label', 'content', 'panel', 'input', 'group', 'item', 'error'],
    states: ['disabled', 'required', 'open', 'closed'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size'],
    optionalParts: ['indicator', 'label', 'content', 'panel', 'input', 'group', 'item', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzCombobox: {
    parts: ['root', 'control', 'input', 'clear', 'trigger', 'icon', 'content', 'viewport', 'item', 'item-indicator', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    states: ['idle', 'disabled', 'invalid', 'required', 'loading', 'open', 'closed', 'checked', 'unchecked'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['clear', 'icon', 'content', 'viewport', 'item', 'item-indicator', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['icon'] },
  },
  DzCommandPalette: {
    parts: ['overlay', 'content', 'control', 'icon', 'input', 'list', 'group', 'group-label', 'item', 'item-label', 'suffix', 'empty'],
    states: ['open', 'closed', 'disabled', 'selected'],
    componentTokens: [],
    riskTier: 'C',
    optionalParts: ['icon', 'group', 'group-label', 'item', 'item-label', 'suffix', 'empty'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzConfirmDialog: {
    parts: ['overlay', 'content', 'viewport', 'icon', 'title', 'description', 'action'],
    states: ['open', 'closed'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant'],
    optionalParts: ['overlay', 'content', 'viewport', 'icon', 'title', 'description', 'action'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzContextMenu: {
    parts: ['content', 'item', 'prefix', 'suffix', 'separator'],
    states: ['open', 'closed', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    optionalParts: ['content', 'item', 'prefix', 'suffix', 'separator'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['suffix'] },
  },
  DzCopyButton: {
    parts: ['root'],
    states: ['idle', 'copied', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzDataGrid: {
    parts: ['root', 'loader', 'empty', 'content', 'header', 'body', 'row', 'cell', 'indicator', 'panel', 'footer'],
    states: ['ready', 'loading', 'selected'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'density'],
    optionalParts: ['loader', 'empty', 'content', 'header', 'body', 'row', 'cell', 'indicator', 'panel', 'footer'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['indicator'] },
  },
  DzDataView: {
    parts: ['root', 'header', 'control', 'list', 'item', 'footer'],
    states: ['disabled'],
    componentTokens: ['--dz-data-view-gap', '--dz-data-view-toolbar-gap', '--dz-data-view-list-divider', '--dz-data-view-list-item-padding-x', '--dz-data-view-list-item-padding-y'],
    riskTier: 'C',
    recipes: ['size'],
    optionalParts: ['header', 'control', 'list', 'item', 'footer'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzDatePicker: {
    parts: ['root', 'control', 'input', 'trigger', 'icon', 'content', 'panel', 'header', 'title', 'action', 'group', 'row', 'cell', 'item', 'error'],
    states: ['idle', 'disabled', 'required', 'invalid', 'open', 'closed', 'selected'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['input', 'content', 'panel', 'header', 'title', 'action', 'group', 'row', 'cell', 'item', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['action', 'icon'] },
  },
  DzDateRangePicker: {
    parts: ['root', 'control', 'input', 'separator', 'trigger', 'icon', 'content', 'panel', 'header', 'title', 'action', 'group', 'row', 'cell', 'item', 'error'],
    states: ['idle', 'disabled', 'required', 'invalid', 'open', 'closed', 'selected'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['input', 'content', 'panel', 'header', 'title', 'action', 'group', 'row', 'cell', 'item', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['action', 'icon'] },
  },
  DzDialog: {
    parts: 'none',
    states: [],
    componentTokens: [],
    riskTier: 'B',
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzDropdownMenu: {
    parts: ['content', 'item', 'prefix', 'suffix', 'separator'],
    states: ['open', 'closed', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    optionalParts: ['content', 'item', 'prefix', 'suffix', 'separator'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['suffix'] },
  },
  DzFab: {
    parts: ['root', 'spinner', 'icon'],
    states: ['idle', 'loading', 'disabled'],
    componentTokens: ['--dz-fab-icon-size', '--dz-fab-offset', '--dz-fab-shadow', '--dz-fab-shadow-hover', '--dz-fab-size', '--dz-fab-z'],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['spinner', 'icon'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzFieldArray: {
    parts: 'none',
    states: [],
    componentTokens: [],
    riskTier: 'B',
    recipes: [],
    optionalParts: [],
    rtl: { mirrors: 'none', keyboard: 'none' },
  },
  DzFileUpload: {
    parts: ['root'],
    states: ['disabled'],
    componentTokens: [],
    riskTier: 'D',
    recipes: ['size'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzHeading: {
    parts: ['root'],
    states: [],
    componentTokens: [],
    riskTier: 'A',
    recipes: ['size'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzIconButton: {
    parts: ['root', 'spinner'],
    states: ['idle', 'loading', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['spinner'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzImageCard: {
    parts: ['root', 'overlay', 'header', 'body', 'footer'],
    states: ['ready'],
    componentTokens: ['--dz-card-radius', '--dz-card-padding', '--dz-card', '--dz-card-foreground', '--dz-card-border-color'],
    riskTier: 'A',
    recipes: ['variant'],
    optionalParts: ['overlay', 'header', 'body', 'footer'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzImageComparison: {
    parts: ['root', 'panel', 'label', 'separator', 'control'],
    states: ['disabled'],
    componentTokens: ['--dz-image-comparison-divider-color', '--dz-image-comparison-divider-width', '--dz-image-comparison-handle-size', '--dz-image-comparison-handle-bg', '--dz-image-comparison-handle-color', '--dz-image-comparison-label-bg', '--dz-image-comparison-label-color'],
    riskTier: 'B',
    recipes: ['orientation'],
    optionalParts: ['panel', 'label'],
    rtl: { mirrors: 'none', keyboard: 'none' },
  },
  DzInfiniteScroll: {
    parts: ['root', 'content', 'loader', 'error', 'hint'],
    states: ['disabled'],
    componentTokens: ['--dz-infinite-scroll-sentinel-size', '--dz-infinite-scroll-status-gap', '--dz-infinite-scroll-status-padding-y'],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['loader', 'error', 'hint'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzInplace: {
    parts: ['root', 'trigger', 'content', 'icon'],
    states: ['display', 'edit', 'disabled'],
    componentTokens: ['--dz-inplace-gap', '--dz-inplace-padding-x', '--dz-inplace-padding-y', '--dz-inplace-radius', '--dz-inplace-ring', '--dz-inplace-hover-bg', '--dz-inplace-hint-color', '--dz-inplace-disabled-opacity'],
    riskTier: 'B',
    recipes: [],
    optionalParts: ['trigger', 'content', 'icon'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['icon'] },
  },
  DzInput: {
    parts: ['root', 'control', 'input', 'prefix', 'suffix', 'spinner', 'clear', 'error'],
    states: ['disabled', 'loading', 'readonly'],
    componentTokens: ['--dz-input-bg', '--dz-input-border', '--dz-input-border-focus', '--dz-input-disabled-opacity', '--dz-input-focus-ring-color', '--dz-input-focus-ring-width', '--dz-input-font-family', '--dz-input-lg-font-size', '--dz-input-lg-height', '--dz-input-lg-padding-x', '--dz-input-md-font-size', '--dz-input-md-height', '--dz-input-md-padding-x', '--dz-input-placeholder', '--dz-input-radius', '--dz-input-sm-font-size', '--dz-input-sm-height', '--dz-input-sm-padding-x', '--dz-input-transition', '--dz-input-xl-font-size', '--dz-input-xl-height', '--dz-input-xl-padding-x', '--dz-input-xs-font-size', '--dz-input-xs-height', '--dz-input-xs-padding-x'],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['prefix', 'suffix', 'spinner', 'clear', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzInputGroup: {
    parts: ['root', 'prefix', 'content', 'suffix'],
    states: ['disabled'],
    componentTokens: [],
    riskTier: 'A',
    recipes: ['size'],
    optionalParts: ['prefix', 'suffix'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzInputMask: {
    parts: ['root', 'control', 'input', 'prefix', 'suffix', 'error'],
    states: ['disabled', 'loading', 'readonly', 'required', 'completed'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['prefix', 'suffix', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzKbd: {
    parts: ['root', 'item', 'separator'],
    states: [],
    componentTokens: ['--dz-kbd-bg', '--dz-kbd-border', '--dz-kbd-fg', '--dz-kbd-font-size', '--dz-kbd-gap', '--dz-kbd-min-size', '--dz-kbd-padding-x', '--dz-kbd-radius', '--dz-kbd-shadow'],
    riskTier: 'A',
    recipes: ['size'],
    optionalParts: ['item', 'separator'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzKnob: {
    parts: ['root', 'control', 'indicator', 'label', 'error'],
    states: ['disabled', 'required', 'readonly', 'loading', 'invalid'],
    componentTokens: ['--dz-knob-range', '--dz-knob-value'],
    riskTier: 'B',
    recipes: ['size', 'tone'],
    optionalParts: ['indicator', 'label', 'error'],
    rtl: { mirrors: 'none', keyboard: 'swap-horizontal' },
  },
  DzLightbox: {
    parts: ['overlay', 'content', 'label', 'close', 'action', 'description'],
    states: ['open', 'closed'],
    componentTokens: [],
    riskTier: 'B',
    optionalParts: ['label', 'action', 'description'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['action'] },
  },
  DzListItem: {
    parts: ['root', 'item-label'],
    states: ['active', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['tone'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzListbox: {
    parts: ['root', 'control', 'input', 'viewport', 'group', 'group-label', 'item', 'icon', 'item-label', 'item-indicator', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    states: ['disabled', 'invalid', 'required', 'readonly', 'loading', 'checked', 'unchecked'],
    componentTokens: ['--dz-listbox-bg', '--dz-listbox-fg', '--dz-listbox-border', '--dz-listbox-radius', '--dz-listbox-active-ring', '--dz-listbox-item-active-bg', '--dz-listbox-item-selected-bg', '--dz-listbox-item-selected-fg'],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['input', 'group', 'group-label', 'item', 'icon', 'item-label', 'item-indicator', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzMegaMenu: {
    parts: ['root', 'list', 'trigger', 'indicator', 'panel', 'group', 'group-label', 'item'],
    states: ['disabled'],
    componentTokens: ['--dz-menu-bar-gap', '--dz-menu-panel-offset', '--dz-menu-panel-padding', '--dz-menu-column-gap', '--dz-menu-column-min-width'],
    riskTier: 'C',
    recipes: ['size', 'orientation'],
    optionalParts: ['trigger', 'indicator', 'panel', 'group', 'group-label', 'item'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['indicator'] },
  },
  DzMention: {
    parts: ['root', 'control', 'input', 'content', 'loader', 'list', 'item', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    states: ['disabled', 'invalid', 'required', 'readonly', 'loading', 'active'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['content', 'loader', 'list', 'item', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzMenu: {
    parts: ['root', 'item', 'item-label', 'separator'],
    states: ['ready', 'active', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['item', 'item-label', 'separator'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzMultiSelect: {
    parts: ['root', 'control', 'input', 'clear', 'trigger', 'icon', 'content', 'viewport', 'item', 'item-indicator', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    states: ['idle', 'disabled', 'invalid', 'required', 'open', 'closed', 'checked', 'unchecked'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['clear', 'content', 'viewport', 'item', 'item-indicator', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['icon'] },
  },
  DzNotification: {
    parts: ['root', 'icon', 'content', 'title', 'description', 'action', 'close'],
    states: ['open', 'closed'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['tone'],
    optionalParts: ['icon', 'description', 'action', 'close'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzNumberInput: {
    parts: ['root', 'control', 'input', 'prefix', 'decrement', 'increment', 'error'],
    states: ['disabled', 'readonly', 'loading', 'required'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['prefix', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzOrderList: {
    parts: ['root', 'group', 'list', 'item', 'control', 'item-label', 'empty'],
    states: ['disabled', 'selected', 'grabbed'],
    componentTokens: ['--dz-order-list-gap', '--dz-order-list-radius', '--dz-order-list-border', '--dz-order-list-control-gap', '--dz-order-list-item-gap', '--dz-order-list-item-bg', '--dz-order-list-item-hover-bg', '--dz-order-list-item-padding-x', '--dz-order-list-item-padding-y', '--dz-order-list-item-selected-bg', '--dz-order-list-item-selected-fg', '--dz-order-list-item-grab-bg', '--dz-order-list-grab-shadow', '--dz-order-list-handle-color', '--dz-order-list-handle-hover', '--dz-order-list-drop-indicator-color', '--dz-order-list-drop-indicator-size', '--dz-order-list-disabled-opacity'],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['group', 'item', 'control', 'item-label', 'empty'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzOtpInput: {
    parts: ['root', 'control', 'input', 'error'],
    states: ['disabled', 'required'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['input', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzPagination: {
    parts: ['root', 'list', 'item', 'action', 'separator'],
    states: ['idle', 'disabled', 'selected'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['item', 'action', 'separator'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['action'] },
  },
  DzPanel: {
    parts: ['root', 'header', 'trigger', 'title', 'indicator', 'action', 'content'],
    states: [],
    componentTokens: ['--dz-panel-bg', '--dz-panel-foreground', '--dz-panel-border', '--dz-panel-shadow', '--dz-panel-radius', '--dz-panel-accent', '--dz-panel-gap', '--dz-panel-padding-x', '--dz-panel-padding-y', '--dz-panel-header-padding-y', '--dz-panel-title-size'],
    riskTier: 'B',
    recipes: ['size', 'variant', 'tone'],
    optionalParts: ['indicator', 'action', 'content'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzPasswordInput: {
    parts: ['root', 'control', 'input', 'prefix', 'spinner', 'toggle', 'error'],
    states: ['disabled', 'loading', 'readonly', 'required'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['prefix', 'spinner', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzPersonaSelector: {
    parts: ['root', 'control', 'input', 'clear', 'trigger', 'icon', 'content', 'viewport', 'item', 'item-indicator', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    states: ['idle', 'disabled', 'invalid', 'required', 'loading', 'open', 'closed', 'checked', 'unchecked'],
    componentTokens: [],
    riskTier: 'C',
    recipes: [],
    optionalParts: ['root', 'control', 'input', 'trigger', 'clear', 'icon', 'content', 'viewport', 'item', 'item-indicator', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['icon'] },
  },
  DzPopconfirm: {
    parts: ['trigger', 'panel', 'header', 'icon', 'body', 'title', 'description', 'action'],
    states: [],
    componentTokens: ['--dz-popconfirm-bg', '--dz-popconfirm-fg', '--dz-popconfirm-border', '--dz-popconfirm-shadow', '--dz-popconfirm-radius', '--dz-popconfirm-width', '--dz-popconfirm-padding'],
    riskTier: 'B',
    recipes: ['tone'],
    optionalParts: ['panel', 'header', 'icon', 'body', 'title', 'description', 'action'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzPopover: {
    parts: ['content', 'indicator'],
    states: ['open', 'closed'],
    componentTokens: [],
    riskTier: 'B',
    optionalParts: ['content', 'indicator'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzProvider: {
    parts: 'none',
    states: [],
    componentTokens: [],
    riskTier: 'B',
    rtl: { mirrors: 'none', keyboard: 'none' },
  },
  DzRadio: {
    parts: ['root', 'control', 'indicator', 'label'],
    states: ['idle', 'checked', 'unchecked', 'disabled', 'invalid', 'active'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['indicator', 'label'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzRadioGroup: {
    parts: ['root'],
    states: ['ready', 'disabled', 'required'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['orientation'],
    optionalParts: [],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzRangeSlider: {
    parts: ['root', 'control', 'indicator', 'label', 'error'],
    states: ['idle', 'disabled', 'required', 'invalid'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size', 'tone', 'orientation'],
    optionalParts: ['indicator', 'label', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['indicator'] },
  },
  DzRating: {
    parts: ['root', 'control', 'item', 'item-indicator', 'error'],
    states: ['disabled', 'required', 'readonly', 'loading', 'invalid'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size', 'tone'],
    optionalParts: ['item', 'item-indicator', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzRelativeTime: {
    parts: ['root'],
    states: [],
    componentTokens: ['--dz-relative-time-font-size'],
    riskTier: 'A',
    recipes: ['tone'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzResizable: {
    parts: ['root', 'panel', 'separator', 'indicator'],
    states: ['inactive', 'hover', 'drag', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['orientation'],
    optionalParts: ['panel', 'separator', 'indicator'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzScrollArea: {
    parts: ['root', 'viewport'],
    states: [],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['orientation'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzSearchInput: {
    parts: ['root', 'control', 'icon', 'input', 'spinner', 'clear', 'error'],
    states: ['disabled', 'readonly', 'loading', 'required'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['spinner', 'clear', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzSegmented: {
    parts: ['root', 'item'],
    states: ['idle', 'disabled', 'on', 'off', 'active'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['item'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzSelect: {
    parts: ['root', 'trigger', 'icon', 'content', 'viewport', 'input', 'item', 'item-indicator', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    states: ['idle', 'open', 'closed', 'disabled', 'invalid', 'checked', 'unchecked'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size'],
    optionalParts: ['icon', 'content', 'viewport', 'input', 'item', 'item-indicator', 'item-label', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['indicator'] },
  },
  DzSheet: {
    parts: ['overlay', 'content', 'title', 'description', 'close'],
    states: ['open', 'closed'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['overlay', 'content', 'title', 'description', 'close'],
    rtl: { mirrors: 'none', keyboard: 'none' },
  },
  DzSidebar: {
    parts: ['root', 'overlay', 'body', 'header', 'footer', 'group', 'group-label', 'item', 'icon', 'item-label', 'suffix'],
    states: ['collapsed', 'expanded', 'active', 'inactive'],
    componentTokens: ['--dz-sidebar-width', '--dz-sidebar-collapsed-width', '--dz-sidebar-bg', '--dz-sidebar-foreground', '--dz-sidebar-border', '--dz-sidebar-transition', '--dz-sidebar-header-bg', '--dz-sidebar-header-border', '--dz-sidebar-header-padding', '--dz-sidebar-footer-bg', '--dz-sidebar-footer-border', '--dz-sidebar-footer-padding', '--dz-sidebar-section-padding-y', '--dz-sidebar-section-title-color', '--dz-sidebar-section-title-font-size', '--dz-sidebar-section-title-letter-spacing', '--dz-sidebar-item-radius', '--dz-sidebar-item-padding-x', '--dz-sidebar-item-padding-y', '--dz-sidebar-item-gap', '--dz-sidebar-item-font-size', '--dz-sidebar-item-font-weight', '--dz-sidebar-item-hover-bg', '--dz-sidebar-item-hover-text', '--dz-sidebar-item-active-bg', '--dz-sidebar-item-active-text', '--dz-sidebar-overlay-bg', '--dz-sidebar-overlay-z-index'],
    riskTier: 'C',
    optionalParts: ['overlay', 'header', 'footer', 'group', 'group-label', 'item', 'icon', 'item-label', 'suffix'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzSlider: {
    parts: ['root', 'control', 'indicator', 'label', 'error'],
    states: ['idle', 'disabled', 'required', 'invalid'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size', 'tone', 'orientation'],
    optionalParts: ['label', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['indicator'] },
  },
  DzSpeedDial: {
    parts: ['root', 'list', 'item'],
    states: [],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['item'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzSpinner: {
    parts: ['root'],
    states: ['loading'],
    componentTokens: [],
    riskTier: 'A',
    recipes: ['size', 'tone'],
    rtl: { mirrors: 'none', keyboard: 'none' },
  },
  DzSplitButton: {
    parts: ['root', 'action', 'trigger'],
    states: ['idle', 'loading', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['action', 'trigger'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzSplitter: {
    parts: ['root', 'panel', 'separator', 'indicator'],
    states: ['inactive', 'hover', 'drag', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['orientation'],
    optionalParts: ['panel', 'separator', 'indicator'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzStatCard: {
    parts: ['root', 'header', 'title', 'icon', 'description'],
    states: ['ready'],
    componentTokens: ['--dz-card-radius', '--dz-card-padding', '--dz-card', '--dz-card-foreground', '--dz-card-border-color'],
    riskTier: 'A',
    recipes: ['variant'],
    optionalParts: ['icon', 'description'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzStepper: {
    parts: ['root'],
    states: ['ready'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['orientation'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzStepperItem: {
    parts: ['root', 'indicator', 'title', 'description'],
    states: ['upcoming', 'active', 'completed'],
    componentTokens: [],
    riskTier: 'B',
    optionalParts: ['indicator', 'title', 'description'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzSwitch: {
    parts: ['root', 'control', 'indicator', 'label'],
    states: ['checked', 'unchecked', 'disabled', 'required'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size'],
    optionalParts: ['label'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['indicator'] },
  },
  DzTable: {
    parts: ['root', 'content', 'title', 'header', 'body', 'row', 'cell', 'footer'],
    states: ['ready', 'loading', 'selected', 'expanded'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['title', 'header', 'body', 'row', 'cell', 'footer'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzTabs: {
    parts: ['root', 'list', 'trigger', 'content', 'close'],
    states: ['ready', 'active', 'inactive', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size', 'variant', 'tone', 'orientation'],
    optionalParts: ['list', 'trigger', 'content', 'close'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzTag: {
    parts: ['root', 'close'],
    states: ['idle', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size', 'variant', 'tone'],
    optionalParts: ['close'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzTagsInput: {
    parts: ['root', 'control', 'input', 'error'],
    states: ['disabled', 'invalid', 'required', 'readonly', 'loading'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['size', 'variant'],
    optionalParts: ['error'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzText: {
    parts: ['root'],
    states: [],
    componentTokens: [],
    riskTier: 'A',
    recipes: ['size', 'tone'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzTextarea: {
    parts: ['root', 'input', 'spinner', 'error'],
    states: ['disabled', 'loading', 'readonly', 'required'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    optionalParts: ['spinner', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzThemeProvider: {
    parts: 'none',
    states: [],
    componentTokens: [],
    riskTier: 'B',
    rtl: { mirrors: 'none', keyboard: 'none' },
  },
  DzTimePicker: {
    parts: ['root', 'control', 'trigger', 'label', 'icon', 'clear', 'content', 'panel', 'list', 'group', 'item', 'input', 'separator', 'footer', 'action', 'error'],
    states: ['disabled', 'required', 'invalid', 'open', 'closed', 'selected'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['label', 'icon', 'clear', 'content', 'panel', 'list', 'group', 'item', 'input', 'separator', 'footer', 'action', 'error'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['icon'] },
  },
  DzToast: {
    parts: ['root', 'indicator', 'title', 'description', 'action', 'close'],
    states: ['open', 'closed'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['tone'],
    optionalParts: ['description', 'action'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzToggleButton: {
    parts: ['root'],
    states: ['idle', 'pressed', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    recipes: ['variant', 'size', 'tone'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzToolbar: {
    parts: ['root', 'group'],
    states: [],
    componentTokens: ['--dz-toolbar-bg', '--dz-toolbar-border', '--dz-toolbar-shadow', '--dz-toolbar-radius', '--dz-toolbar-gap', '--dz-toolbar-padding-x', '--dz-toolbar-padding-y', '--dz-toolbar-sticky-z'],
    riskTier: 'B',
    recipes: ['size', 'variant', 'orientation'],
    optionalParts: ['group'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzTooltip: {
    parts: ['content', 'indicator'],
    states: ['instant-open', 'delayed-open', 'closed'],
    componentTokens: [],
    riskTier: 'B',
    optionalParts: ['content', 'indicator'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzTour: {
    parts: ['overlay', 'panel', 'header', 'title', 'description', 'footer', 'list', 'item-indicator', 'action'],
    states: [],
    componentTokens: ['--dz-tour-mask', '--dz-tour-radius'],
    riskTier: 'C',
    optionalParts: ['overlay', 'panel', 'header', 'title', 'description', 'footer', 'list', 'item-indicator', 'action'],
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
  DzTransfer: {
    parts: ['root', 'control', 'list', 'header', 'hint', 'input', 'body', 'item', 'item-indicator', 'item-label', 'empty', 'group', 'action', 'icon', 'error', 'options-state', 'options-message', 'options-retry'],
    states: ['disabled', 'invalid', 'required', 'checked'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size'],
    optionalParts: ['list', 'header', 'hint', 'input', 'body', 'item', 'item-indicator', 'item-label', 'empty', 'action', 'icon', 'error', 'options-state', 'options-message', 'options-retry'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['icon'] },
  },
  DzTree: {
    parts: ['root', 'empty'],
    states: ['ready', 'loading', 'disabled'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size'],
    optionalParts: ['empty'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal' },
  },
  DzTreeItem: {
    parts: ['root', 'item', 'indicator', 'control', 'item-label', 'group'],
    states: ['open', 'closed', 'checked', 'unchecked', 'disabled'],
    componentTokens: [],
    riskTier: 'B',
    optionalParts: ['control', 'item-label', 'group'],
    rtl: { mirrors: 'layout', keyboard: 'swap-horizontal', icons: ['indicator'] },
  },
  DzTreeSelect: {
    parts: ['root', 'trigger', 'label', 'icon', 'content', 'indicator', 'input', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    states: ['idle', 'open', 'closed', 'disabled', 'invalid', 'readonly', 'required', 'loading', 'checked', 'unchecked', 'indeterminate'],
    componentTokens: [],
    riskTier: 'C',
    recipes: ['size', 'variant'],
    optionalParts: ['content', 'indicator', 'input', 'empty', 'error', 'options-state', 'options-message', 'options-retry'],
    rtl: { mirrors: 'layout', keyboard: 'none', icons: ['icon'] },
  },
  DzVisuallyHidden: {
    parts: ['root'],
    states: [],
    componentTokens: [],
    riskTier: 'A',
    rtl: { mirrors: 'layout', keyboard: 'none' },
  },
}
