/**
 * AUTO-GENERATED — do not edit.
 *
 * Written by `yarn generate:matrix-targets` from
 * packages/core/docs/quality-matrix.json and packages/core/stories/.
 *
 * The browser matrix (TASK-OSS-P5-03) drives every Tier B–D component through
 * three engines and five conditions. A component with `story: null` has no
 * story to drive and is reported as `unrun` — visible, not skipped.
 */

/** One component's browser-matrix target. */
export interface MatrixTarget {
  readonly component: string
  readonly family: string
  readonly tier: 'A' | 'B' | 'C' | 'D'
  readonly traits: readonly ('teleports' | 'drags' | 'dataset')[]
  /** Storybook story id, or null when the component has no story to drive. */
  readonly story: string | null
}

export const MATRIX_TARGETS: readonly MatrixTarget[] = [
  { component: 'DzAccordion', family: 'data', tier: 'B', traits: [], story: 'core-data-dzaccordion--default' },
  { component: 'DzAffix', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzaffix--affix-top' },
  { component: 'DzAlert', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzalert--default' },
  { component: 'DzAnchor', family: 'navigation', tier: 'B', traits: ['dataset'], story: 'core-navigation-dzanchor--default' },
  { component: 'DzAnimatedNumber', family: 'data', tier: 'A', traits: [], story: 'core-data-dzanimatednumber--integer' },
  { component: 'DzAppShell', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzappshell--default' },
  { component: 'DzAspectRatio', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzaspectratio--default' },
  { component: 'DzAsyncBoundary', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzasyncboundary--default' },
  { component: 'DzAvatar', family: 'media', tier: 'A', traits: [], story: 'core-media-dzavatar--default' },
  { component: 'DzAvatarGroup', family: 'media', tier: 'A', traits: ['dataset'], story: 'core-media-dzavatargroup--default' },
  { component: 'DzBackTop', family: 'navigation', tier: 'B', traits: [], story: 'core-navigation-dzbacktop--default' },
  { component: 'DzBadge', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzbadge--default' },
  { component: 'DzBlockUI', family: 'feedback', tier: 'B', traits: ['teleports'], story: 'core-feedback-dzblockui--panel-block' },
  { component: 'DzBlockquote', family: 'typography', tier: 'A', traits: [], story: 'core-typography-dzblockquote--default' },
  { component: 'DzBreadcrumb', family: 'navigation', tier: 'B', traits: ['dataset'], story: 'core-navigation-dzbreadcrumb--default' },
  { component: 'DzButton', family: 'buttons', tier: 'B', traits: [], story: 'core-buttons-dzbutton--default' },
  { component: 'DzButtonGroup', family: 'buttons', tier: 'A', traits: [], story: 'core-buttons-dzbuttongroup--default' },
  { component: 'DzCalendar', family: 'data', tier: 'C', traits: [], story: 'core-data-dzcalendar--month' },
  { component: 'DzCaption', family: 'typography', tier: 'A', traits: [], story: 'core-typography-dzcaption--default' },
  { component: 'DzCard', family: 'cards', tier: 'B', traits: [], story: 'core-cards-dzcard--default' },
  { component: 'DzCarousel', family: 'media', tier: 'B', traits: ['dataset'], story: 'core-media-dzcarousel--default' },
  { component: 'DzCascader', family: 'forms', tier: 'C', traits: ['dataset', 'teleports'], story: 'core-forms-dzcascader--default' },
  { component: 'DzCheckbox', family: 'forms', tier: 'B', traits: [], story: 'core-forms-dzcheckbox--default' },
  { component: 'DzCheckboxGroup', family: 'forms', tier: 'B', traits: [], story: 'core-forms-dzcheckboxgroup--default' },
  { component: 'DzChip', family: 'data', tier: 'B', traits: [], story: 'core-data-dzchip--default' },
  { component: 'DzCode', family: 'typography', tier: 'A', traits: [], story: 'core-typography-dzcode--default' },
  { component: 'DzCodeBlock', family: 'data', tier: 'A', traits: [], story: 'core-data-dzcodeblock--default' },
  { component: 'DzCollapse', family: 'layout', tier: 'B', traits: [], story: 'core-layout-dzcollapse--default' },
  { component: 'DzColorModeToggle', family: 'navigation', tier: 'B', traits: [], story: 'core-navigation-dzcolormodetoggle--icon-cycle' },
  { component: 'DzColorPicker', family: 'forms', tier: 'C', traits: ['teleports'], story: 'core-forms-dzcolorpicker--default' },
  { component: 'DzCombobox', family: 'forms', tier: 'C', traits: ['dataset', 'teleports'], story: 'core-forms-dzcombobox--default' },
  { component: 'DzCommandPalette', family: 'overlays', tier: 'C', traits: ['dataset', 'teleports'], story: 'core-overlays-dzcommandpalette--default' },
  { component: 'DzConfirmDialog', family: 'overlays', tier: 'B', traits: ['teleports'], story: 'core-overlays-dzconfirmdialog--default' },
  { component: 'DzContainer', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzcontainer--default' },
  { component: 'DzContextMenu', family: 'overlays', tier: 'B', traits: ['teleports'], story: 'core-overlays-dzcontextmenu--default' },
  { component: 'DzCopyButton', family: 'buttons', tier: 'B', traits: [], story: 'core-buttons-dzcopybutton--default' },
  { component: 'DzCountdown', family: 'data', tier: 'A', traits: [], story: 'core-data-dzcountdown--to-deadline' },
  { component: 'DzDataGrid', family: 'data', tier: 'C', traits: ['dataset', 'teleports'], story: 'core-data-dzdatagrid--default' },
  { component: 'DzDataView', family: 'data', tier: 'C', traits: ['dataset'], story: 'core-data-dzdataview--list-layout' },
  { component: 'DzDatePicker', family: 'forms', tier: 'C', traits: [], story: 'core-forms-dzdatepicker--default' },
  { component: 'DzDateRangePicker', family: 'forms', tier: 'C', traits: [], story: 'core-forms-dzdaterangepicker--default' },
  { component: 'DzDeferredContent', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzdeferredcontent--deferred-image' },
  { component: 'DzDescriptions', family: 'data', tier: 'A', traits: ['dataset'], story: 'core-data-dzdescriptions--default' },
  { component: 'DzDialog', family: 'overlays', tier: 'B', traits: ['teleports'], story: 'core-overlays-dzdialog--default' },
  { component: 'DzDivider', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzdivider--default' },
  { component: 'DzDropdownMenu', family: 'overlays', tier: 'B', traits: ['teleports'], story: 'core-overlays-dzdropdownmenu--default' },
  { component: 'DzEmoji', family: 'media', tier: 'A', traits: [], story: 'core-media-dzemoji--default' },
  { component: 'DzEmpty', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzempty--default' },
  { component: 'DzErrorBoundary', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzerrorboundary--default' },
  { component: 'DzFab', family: 'buttons', tier: 'B', traits: [], story: 'core-buttons-dzfab--default' },
  { component: 'DzFieldArray', family: 'forms', tier: 'B', traits: ['dataset'], story: 'core-forms-dzfieldarray--default' },
  { component: 'DzFileUpload', family: 'forms', tier: 'D', traits: ['drags'], story: 'core-forms-dzfileupload--default' },
  { component: 'DzFlex', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzflex--default' },
  { component: 'DzFloatLabel', family: 'forms', tier: 'A', traits: [], story: 'core-forms-dzfloatlabel--over-input' },
  { component: 'DzFormField', family: 'forms', tier: 'A', traits: [], story: 'core-forms-dzformfield--default' },
  { component: 'DzGrid', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzgrid--default' },
  { component: 'DzHeading', family: 'typography', tier: 'A', traits: [], story: 'core-typography-dzheading--default' },
  { component: 'DzIcon', family: 'media', tier: 'A', traits: [], story: 'core-media-dzicon--default' },
  { component: 'DzIconButton', family: 'buttons', tier: 'B', traits: [], story: 'core-buttons-dziconbutton--default' },
  { component: 'DzImage', family: 'media', tier: 'A', traits: [], story: 'core-media-dzimage--default' },
  { component: 'DzImageCard', family: 'cards', tier: 'A', traits: [], story: 'core-cards-dzimagecard--default' },
  { component: 'DzImageComparison', family: 'media', tier: 'B', traits: ['drags'], story: 'core-media-dzimagecomparison--horizontal' },
  { component: 'DzInfiniteScroll', family: 'data', tier: 'B', traits: ['dataset'], story: 'core-data-dzinfinitescroll--basic-feed' },
  { component: 'DzInplace', family: 'forms', tier: 'B', traits: [], story: 'core-forms-dzinplace--text-field' },
  { component: 'DzInput', family: 'inputs', tier: 'B', traits: [], story: 'core-inputs-dzinput--default' },
  { component: 'DzInputGroup', family: 'inputs', tier: 'A', traits: [], story: 'core-inputs-dzinputgroup--default' },
  { component: 'DzInputMask', family: 'inputs', tier: 'B', traits: [], story: 'core-inputs-dzinputmask--phone' },
  { component: 'DzKbd', family: 'typography', tier: 'A', traits: [], story: 'core-typography-dzkbd--single-key' },
  { component: 'DzKnob', family: 'forms', tier: 'B', traits: ['drags'], story: 'core-forms-dzknob--default' },
  { component: 'DzLightbox', family: 'media', tier: 'B', traits: ['teleports'], story: 'core-media-dzlightbox--default' },
  { component: 'DzList', family: 'data', tier: 'A', traits: ['dataset'], story: 'core-data-dzlist--default' },
  { component: 'DzListItem', family: 'data', tier: 'B', traits: [], story: 'core-data-dzlistitem--default' },
  { component: 'DzListbox', family: 'forms', tier: 'B', traits: ['dataset'], story: 'core-forms-dzlistbox--single' },
  { component: 'DzMasonry', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzmasonry--default' },
  { component: 'DzMegaMenu', family: 'navigation', tier: 'C', traits: ['dataset'], story: 'core-navigation-dzmegamenu--horizontal' },
  { component: 'DzMention', family: 'forms', tier: 'C', traits: ['dataset'], story: 'core-forms-dzmention--default' },
  { component: 'DzMenu', family: 'navigation', tier: 'B', traits: ['dataset'], story: 'core-navigation-dzmenu--default' },
  { component: 'DzMeterGroup', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzmetergroup--default' },
  { component: 'DzMultiSelect', family: 'forms', tier: 'C', traits: ['dataset', 'teleports'], story: 'core-forms-dzmultiselect--default' },
  { component: 'DzNotification', family: 'feedback', tier: 'B', traits: [], story: 'core-feedback-dznotification--default' },
  { component: 'DzNumberInput', family: 'inputs', tier: 'B', traits: [], story: 'core-inputs-dznumberinput--default' },
  { component: 'DzOrderList', family: 'data', tier: 'C', traits: ['dataset', 'drags'], story: 'core-data-dzorderlist--default' },
  { component: 'DzOtpInput', family: 'inputs', tier: 'B', traits: [], story: 'core-inputs-dzotpinput--default' },
  { component: 'DzPageHero', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzpagehero--bare' },
  { component: 'DzPagination', family: 'navigation', tier: 'B', traits: [], story: 'core-navigation-dzpagination--default' },
  { component: 'DzPanel', family: 'layout', tier: 'B', traits: [], story: 'core-layout-dzpanel--outlined' },
  { component: 'DzPasswordInput', family: 'inputs', tier: 'B', traits: [], story: 'core-inputs-dzpasswordinput--default' },
  { component: 'DzPersonaSelector', family: 'forms', tier: 'C', traits: ['dataset', 'teleports'], story: 'core-forms-dzpersonaselector--default' },
  { component: 'DzPopconfirm', family: 'overlays', tier: 'B', traits: ['teleports'], story: 'core-overlays-dzpopconfirm--default' },
  { component: 'DzPopover', family: 'overlays', tier: 'B', traits: ['teleports'], story: 'core-overlays-dzpopover--default' },
  { component: 'DzProgress', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzprogress--default' },
  { component: 'DzProvider', family: 'providers', tier: 'B', traits: [], story: 'core-providers-dzprovider--default' },
  { component: 'DzQRCode', family: 'media', tier: 'A', traits: [], story: 'core-media-dzqrcode--default' },
  { component: 'DzRadio', family: 'forms', tier: 'B', traits: [], story: 'core-forms-dzradio--default' },
  { component: 'DzRadioGroup', family: 'forms', tier: 'B', traits: [], story: 'core-forms-dzradiogroup--default' },
  { component: 'DzRangeSlider', family: 'forms', tier: 'B', traits: ['drags'], story: 'core-forms-dzrangeslider--default' },
  { component: 'DzRating', family: 'forms', tier: 'B', traits: [], story: 'core-forms-dzrating--default' },
  { component: 'DzRelativeTime', family: 'typography', tier: 'A', traits: ['teleports'], story: 'core-typography-dzrelativetime--just-now' },
  { component: 'DzResizable', family: 'layout', tier: 'B', traits: ['drags'], story: 'core-layout-dzresizable--default' },
  { component: 'DzResult', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzresult--default' },
  { component: 'DzRunStatusBadge', family: 'feedback', tier: 'A', traits: [], story: null },
  { component: 'DzScrollArea', family: 'layout', tier: 'B', traits: [], story: 'core-layout-dzscrollarea--default' },
  { component: 'DzScrollProgress', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzscrollprogress--top-bar' },
  { component: 'DzSearchInput', family: 'inputs', tier: 'B', traits: [], story: 'core-inputs-dzsearchinput--default' },
  { component: 'DzSegmented', family: 'navigation', tier: 'B', traits: [], story: 'core-navigation-dzsegmented--default' },
  { component: 'DzSelect', family: 'forms', tier: 'B', traits: ['dataset', 'teleports'], story: 'core-forms-dzselect--default' },
  { component: 'DzSheet', family: 'overlays', tier: 'B', traits: ['teleports'], story: 'core-overlays-dzsheet--default' },
  { component: 'DzSidebar', family: 'navigation', tier: 'C', traits: ['dataset', 'teleports'], story: 'core-navigation-dzsidebar--default' },
  { component: 'DzSkeleton', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzskeleton--default' },
  { component: 'DzSlider', family: 'forms', tier: 'B', traits: ['drags'], story: 'core-forms-dzslider--default' },
  { component: 'DzSpacer', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzspacer--default' },
  { component: 'DzSpeedDial', family: 'buttons', tier: 'B', traits: ['dataset', 'teleports'], story: 'core-buttons-dzspeeddial--fab' },
  { component: 'DzSpinner', family: 'feedback', tier: 'A', traits: [], story: 'core-feedback-dzspinner--default' },
  { component: 'DzSplitButton', family: 'buttons', tier: 'B', traits: [], story: 'core-buttons-dzsplitbutton--default' },
  { component: 'DzSplitter', family: 'layout', tier: 'B', traits: ['drags'], story: 'core-layout-dzsplitter--default' },
  { component: 'DzStack', family: 'layout', tier: 'A', traits: [], story: 'core-layout-dzstack--default' },
  { component: 'DzStatCard', family: 'cards', tier: 'A', traits: [], story: 'core-cards-dzstatcard--default' },
  { component: 'DzStepper', family: 'navigation', tier: 'B', traits: [], story: 'core-navigation-dzstepper--default' },
  { component: 'DzStepperItem', family: 'navigation', tier: 'B', traits: [], story: 'core-navigation-dzstepperitem--default' },
  { component: 'DzSwitch', family: 'forms', tier: 'B', traits: [], story: 'core-forms-dzswitch--default' },
  { component: 'DzTable', family: 'data', tier: 'C', traits: ['dataset', 'drags'], story: 'core-data-dztable--default' },
  { component: 'DzTabs', family: 'navigation', tier: 'B', traits: [], story: 'core-navigation-dztabs--default' },
  { component: 'DzTag', family: 'data', tier: 'B', traits: [], story: 'core-data-dztag--default' },
  { component: 'DzTagsInput', family: 'forms', tier: 'B', traits: ['dataset'], story: 'core-forms-dztagsinput--default' },
  { component: 'DzText', family: 'typography', tier: 'A', traits: [], story: 'core-typography-dztext--default' },
  { component: 'DzTextarea', family: 'inputs', tier: 'B', traits: [], story: 'core-inputs-dztextarea--default' },
  { component: 'DzThemeProvider', family: 'providers', tier: 'B', traits: [], story: null },
  { component: 'DzTimePicker', family: 'forms', tier: 'C', traits: ['teleports'], story: 'core-forms-dztimepicker--default' },
  { component: 'DzTimeline', family: 'data', tier: 'A', traits: ['dataset'], story: 'core-data-dztimeline--default' },
  { component: 'DzTimelineItem', family: 'data', tier: 'A', traits: [], story: 'core-data-dztimelineitem--default' },
  { component: 'DzToast', family: 'feedback', tier: 'B', traits: [], story: 'core-feedback-dztoast--default' },
  { component: 'DzToggleButton', family: 'buttons', tier: 'B', traits: [], story: 'core-buttons-dztogglebutton--default' },
  { component: 'DzTokenProgressBar', family: 'feedback', tier: 'A', traits: [], story: null },
  { component: 'DzToolbar', family: 'layout', tier: 'B', traits: [], story: 'core-layout-dztoolbar--default' },
  { component: 'DzTooltip', family: 'overlays', tier: 'B', traits: ['teleports'], story: 'core-overlays-dztooltip--default' },
  { component: 'DzTour', family: 'overlays', tier: 'C', traits: ['dataset', 'teleports'], story: 'core-overlays-dztour--basic-three-step' },
  { component: 'DzTransfer', family: 'forms', tier: 'C', traits: ['dataset'], story: 'core-forms-dztransfer--default' },
  { component: 'DzTree', family: 'data', tier: 'C', traits: ['dataset'], story: 'core-data-dztree--default' },
  { component: 'DzTreeItem', family: 'data', tier: 'B', traits: [], story: 'core-data-dztreeitem--default' },
  { component: 'DzTreeSelect', family: 'forms', tier: 'C', traits: ['dataset', 'teleports'], story: 'core-forms-dztreeselect--single' },
  { component: 'DzVisuallyHidden', family: 'typography', tier: 'A', traits: [], story: 'core-typography-dzvisuallyhidden--default' },
  { component: 'DzWatermark', family: 'media', tier: 'A', traits: [], story: 'core-media-dzwatermark--text-mark' },
  { component: 'GovernanceBadge', family: 'feedback', tier: 'A', traits: [], story: null },
  { component: 'TeamMemberBadge', family: 'feedback', tier: 'A', traits: [], story: null },
]
