/**
 * The page the strict-CSP lane loads (TASK-R2-O4, closing TASK-N1-O5's O5-5).
 *
 * Four things are on it, and each is here for a reason the lane can state:
 *
 * 1. **`DzProvider nonce="…"`** — ADR-20 §8's nonce is the mechanism by which a
 *    library `<style>` survives `style-src 'self' 'nonce-…'`. The server
 *    generates the nonce per request and writes it into both the header and
 *    this page's data attribute, so the two cannot drift.
 * 2. **`DzThemeProvider`** — the one component in Core that injects a `<style>`
 *    element at runtime (the transition suppressor on a theme change). If a
 *    strict policy drops it, the symptom is a colour sweep nobody can reproduce
 *    locally, which is exactly why `nonce` is part of the provider contract.
 * 3. **`DzFileUpload`** — the Tier D component. N1-O5's `csp-fixture.spec.ts`
 *    proves it *emits* no construct a strict policy blocks; jsdom does not
 *    enforce CSP, so that spec cannot prove a browser served a real header
 *    accepted the page. This is the half that was owed.
 * 4. **Two `DzButton`s** — one with an allowed `href`, one with
 *    `javascript:alert(1)`. The URL policy is a jsdom result everywhere else in
 *    this repo; a browser costs nothing extra here and the assertion is the one
 *    that matters — the hostile URL is not in the DOM.
 *
 * Plus one deliberate control: `DzButton` still carries
 * `style="contain: layout style"`, which finding F-C1 says a strict `style-src`
 * drops. The lane measures that rather than avoiding it — see `csp.spec.ts`.
 */

import { createApp, h } from 'vue'
import DzButton from '../../../../packages/core/src/components/buttons/DzButton.vue'
import DzFileUpload from '../../../../packages/core/src/components/forms/DzFileUpload.vue'
import DzProvider from '../../../../packages/core/src/providers/DzProvider.vue'
import DzThemeProvider from '../../../../packages/core/src/providers/DzThemeProvider.vue'
// eslint-disable-next-line antfu/no-import-dist -- the BUILT stylesheet is the subject. `@dzup-ui/tokens` has no source CSS: `tokens.css` is generated by `yarn tokens:generate`, and a CSP claim is about the sheet a consumer receives.
import '../../../../packages/tokens/dist/tokens.css'
import '../../../../packages/core/src/styles/base.css'

/** Written by the server into `<html data-dz-nonce>`, matching the header. */
const nonce = document.documentElement.dataset.dzNonce ?? ''

const app = createApp({
  setup() {
    return () =>
      h(
        DzProvider,
        { nonce, theme: { default: 'light', persist: false } },
        {
          default: () => [
            h(
              DzThemeProvider,
              { defaultTheme: 'light' },
              {
                default: () => [
                  h('div', { id: 'upload-host' }, [
                    h(DzFileUpload, { accept: '.txt', ariaLabel: 'Attach evidence' }),
                  ]),
                  h('div', { id: 'button-host' }, [
                    h(
                      DzButton,
                      { id: 'allowed-link', href: '/docs/getting-started' },
                      { default: () => 'Allowed' },
                    ),
                    h(
                      DzButton,
                      { id: 'refused-link', href: 'javascript:alert(1)' },
                      { default: () => 'Refused' },
                    ),
                  ]),
                ],
              },
            ),
          ],
        },
      )
  },
})

app.mount('#app')

// The lane waits on this rather than on a timeout: a CSP violation that stops
// the bundle would otherwise look like a slow mount.
document.documentElement.setAttribute('data-dz-mounted', 'true')
