nodeLinker: node-modules

packageExtensions:
  "@antfu/eslint-config@*":
    dependencies:
      "@typescript-eslint/rule-tester": "^8.57.2"
      "@typescript-eslint/typescript-estree": "^8.57.2"
      "@typescript-eslint/utils": "^8.57.2"
      "@vue/compiler-sfc": "^3.5.31"
      typescript: "^5.9.3"
  "@floating-ui/vue@*":
    dependencies:
      vue: "*"
  "@storybook/addon-docs@*":
    dependencies:
      "@types/react": "*"
  "@storybook/addon-vitest@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/vue3-vite@*":
    dependencies:
      vue: "*"
  eslint-plugin-n@*:
    dependencies:
      typescript: "^5.9.3"
  eslint-plugin-perfectionist@*:
    dependencies:
      typescript: "^5.9.3"
  storybook@*:
    dependencies:
      "@testing-library/dom": "*"
      react: "*"
      react-dom: "*"
