approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@antfu/eslint-config@*":
    dependencies:
      "@typescript-eslint/rule-tester": ^8.57.2
      "@typescript-eslint/typescript-estree": ^8.57.2
      "@typescript-eslint/utils": ^8.57.2
      "@vue/compiler-sfc": ^3.5.31
      typescript: ^5.9.3
  "@floating-ui/vue@*":
    dependencies:
      vue: "*"
  "@nuxt/devtools@*":
    dependencies:
      vite: ^5.0.0
      vue: "*"
  "@storybook/addon-docs@*":
    dependencies:
      "@types/react": "*"
  "@storybook/addon-vitest@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/vue3-vite@*":
    dependencies:
      vue: "*"
  "@vue/devtools-core@*":
    dependencies:
      vite: ^5.0.0
  eslint-plugin-n@*:
    dependencies:
      typescript: ^5.9.3
  eslint-plugin-perfectionist@*:
    dependencies:
      typescript: ^5.9.3
  nuxt@*:
    dependencies:
      vite: ^5.0.0
  storybook@*:
    dependencies:
      "@testing-library/dom": "*"
      react: "*"
      react-dom: "*"
