/**
 * Token Generation Script
 *
 * Reads all token definitions and generates:
 * - dist/tokens.css       — All CSS custom properties
 * - dist/tokens.d.ts      — TypeScript type definitions
 * - dist/tailwind-theme.js — Tailwind CSS 4 theme extension
 * - dist/tailwind-theme.d.ts — Types for the Tailwind theme
 *
 * Run via: yarn workspace @dzup-ui/tokens generate
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { APPSHELL_TOKENS } from './component/appshell.js'
import { BADGE_TOKENS } from './component/badge.js'
// Component
import { BUTTON_TOKENS } from './component/button.js'
import { CARD_TOKENS } from './component/card.js'
import { CONTROL_TOKENS } from './component/control.js'
import { DIALOG_TOKENS } from './component/dialog.js'
import { INPUT_TOKENS } from './component/input.js'
import { SIDEBAR_TOKENS } from './component/sidebar.js'
import { generateBreakpointCssVars } from './primitives/breakpoints.js'
// Primitives
import { generateColorCssVars } from './primitives/colors.js'
import { generateRadiusCssVars } from './primitives/radius.js'

import { generateShadowCssVars, generateShadowDarkCssVars } from './primitives/shadows.js'
import { generateSpacingCssVars } from './primitives/spacing.js'

import { generateTransitionCssVars } from './primitives/transitions.js'
import { generateTypographyCssVars } from './primitives/typography.js'
import { generateZIndexCssVars } from './primitives/z-index.js'
import { DARK_SEMANTIC_TOKENS } from './semantic/dark.js'
// Semantic
import { LIGHT_SEMANTIC_TOKENS } from './semantic/light.js'

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

const __dirname = dirname(fileURLToPath(import.meta.url))
const DIST_DIR = resolve(__dirname, '..', 'dist')

function formatVars(vars: Record<string, string>, indent: string = '  '): string {
  return Object.entries(vars)
    .map(([key, value]) => `${indent}${key}: ${value};`)
    .join('\n')
}

function extractTokenNames(vars: Record<string, string>): string[] {
  return Object.keys(vars)
}

// --------------------------------------------------------------------------
// CSS Generation
// --------------------------------------------------------------------------

function generateCss(): string {
  const primitiveColors = generateColorCssVars()
  const spacing = generateSpacingCssVars()
  const typography = generateTypographyCssVars()
  const radius = generateRadiusCssVars()
  const shadows = generateShadowCssVars()
  const shadowsDark = generateShadowDarkCssVars()
  const transitions = generateTransitionCssVars()
  const zIndex = generateZIndexCssVars()
  const breakpoints = generateBreakpointCssVars()

  const componentTokens = {
    ...BUTTON_TOKENS,
    ...CONTROL_TOKENS,
    ...INPUT_TOKENS,
    ...CARD_TOKENS,
    ...BADGE_TOKENS,
    ...DIALOG_TOKENS,
    ...SIDEBAR_TOKENS,
    ...APPSHELL_TOKENS,
  }

  return `/**
 * @dzup-ui/tokens — Generated CSS Custom Properties
 *
 * DO NOT EDIT MANUALLY.
 * Generated by: yarn workspace @dzup-ui/tokens generate
 * Source: packages/tokens/src/
 *
 * Three-tier token system:
 *   Tier 1 — Primitive: raw palette and scale values
 *   Tier 2 — Semantic: intent-based mappings (light/dark)
 *   Tier 3 — Component: per-component overrides
 *
 * All token declarations are wrapped in @layer dz-tokens so that
 * consumer utilities (unlayered) can override them without !important.
 * The layer order is declared in packages/core/src/styles/base.css:
 *   @layer dz-tokens, dz-base, dz-components;
 */

@layer dz-tokens {

/* ==========================================================================
   Tier 1: Primitive Tokens
   ========================================================================== */

:root {
  /* ── Colors (OKLCH) ── */
${formatVars(primitiveColors)}

  /* ── Spacing ── */
${formatVars(spacing)}

  /* ── Typography ── */
${formatVars(typography)}

  /* ── Border Radius ── */
${formatVars(radius)}

  /* ── Shadows ── */
${formatVars(shadows)}

  /* ── Transitions ── */
${formatVars(transitions)}

  /* ── Z-Index ── */
${formatVars(zIndex)}

  /* ── Breakpoints ── */
${formatVars(breakpoints)}
}

/* ==========================================================================
   Tier 2: Semantic Tokens — Light Theme (default)
   ========================================================================== */

:root, [data-theme="light"] {
${formatVars(LIGHT_SEMANTIC_TOKENS)}
}

/* ==========================================================================
   Tier 2: Semantic Tokens — Dark Theme
   ========================================================================== */

[data-theme="dark"] {
${formatVars(DARK_SEMANTIC_TOKENS)}

  /* ── Dark mode shadow overrides (increased opacity) ── */
${formatVars(shadowsDark)}
}

/* ==========================================================================
   System preference fallback (when no data-theme is set explicitly)
   ========================================================================== */

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${formatVars(DARK_SEMANTIC_TOKENS, '    ')}

    /* ── Dark mode shadow overrides ── */
${formatVars(shadowsDark, '    ')}
  }
}

/* ==========================================================================
   Tier 3: Component Tokens
   ========================================================================== */

:root {
${formatVars(componentTokens)}
}

} /* end @layer dz-tokens */

/* ==========================================================================
   Reduced Motion
   Kept outside @layer — these safety overrides must always win.
   ========================================================================== */

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
`
}

// --------------------------------------------------------------------------
// TypeScript Types Generation
// --------------------------------------------------------------------------

function generateTypes(): string {
  const allPrimitiveVars = {
    ...generateColorCssVars(),
    ...generateSpacingCssVars(),
    ...generateTypographyCssVars(),
    ...generateRadiusCssVars(),
    ...generateShadowCssVars(),
    ...generateTransitionCssVars(),
    ...generateZIndexCssVars(),
    ...generateBreakpointCssVars(),
  }

  const componentTokens = {
    ...BUTTON_TOKENS,
    ...CONTROL_TOKENS,
    ...INPUT_TOKENS,
    ...CARD_TOKENS,
    ...BADGE_TOKENS,
    ...DIALOG_TOKENS,
    ...SIDEBAR_TOKENS,
    ...APPSHELL_TOKENS,
  }

  const primitiveNames = extractTokenNames(allPrimitiveVars)
  const semanticNames = extractTokenNames(LIGHT_SEMANTIC_TOKENS)
  const componentNames = extractTokenNames(componentTokens)

  function toUnionType(names: string[]): string {
    return names.map(n => `  | '${n}'`).join('\n')
  }

  return `/**
 * @dzup-ui/tokens — Generated TypeScript Definitions
 *
 * DO NOT EDIT MANUALLY.
 * Generated by: yarn workspace @dzup-ui/tokens generate
 */

/** All primitive token CSS custom property names */
export type PrimitiveToken =
${toUnionType(primitiveNames)};

/** All semantic token CSS custom property names */
export type SemanticToken =
${toUnionType(semanticNames)};

/** All component token CSS custom property names */
export type ComponentToken =
${toUnionType(componentNames)};

/** Union of all design token CSS custom property names */
export type DesignToken = PrimitiveToken | SemanticToken | ComponentToken;

/** Theme mode */
export type ThemeMode = 'light' | 'dark' | 'system';

/** Resolved theme (no 'system') */
export type ResolvedTheme = 'light' | 'dark';
`
}

// --------------------------------------------------------------------------
// Tailwind CSS 4 Theme Generation
// --------------------------------------------------------------------------

function generateTailwindTheme(): string {
  const colorVars = generateColorCssVars()
  const spacing = generateSpacingCssVars()
  const radius = generateRadiusCssVars()
  const shadows = generateShadowCssVars()

  // Build color entries: primary-50 through primary-950, etc.
  const colorEntries: Record<string, Record<string, string>> = {}
  for (const key of Object.keys(colorVars)) {
    // --dz-colors-{palette}-{shade} -> palette, shade
    const match = key.match(/^--dz-colors-(\w+)-(\d+)$/)
    if (match) {
      const palette = match[1] ?? ''
      const shade = match[2] ?? ''
      if (!colorEntries[palette]) {
        colorEntries[palette] = {}
      }
      const paletteObj = colorEntries[palette]
      if (paletteObj) {
        paletteObj[shade] = `var(${key})`
      }
    }
  }

  // Semantic color mappings for Tailwind
  const semanticColors: Record<string, string | Record<string, string>> = {
    background: 'var(--dz-background)',
    foreground: 'var(--dz-foreground)',
    surface: 'var(--dz-surface)',
    muted: {
      DEFAULT: 'var(--dz-muted)',
      foreground: 'var(--dz-muted-foreground)',
    },
    border: 'var(--dz-border)',
    ring: 'var(--dz-ring)',
    primary: {
      ...colorEntries.primary,
      DEFAULT: 'var(--dz-primary)',
      foreground: 'var(--dz-primary-foreground)',
    },
    secondary: {
      ...colorEntries.secondary,
      DEFAULT: 'var(--dz-secondary)',
      foreground: 'var(--dz-secondary-foreground)',
    },
    destructive: {
      DEFAULT: 'var(--dz-destructive)',
      foreground: 'var(--dz-destructive-foreground)',
    },
    success: {
      ...colorEntries.success,
      DEFAULT: 'var(--dz-success)',
      foreground: 'var(--dz-success-foreground)',
    },
    warning: {
      ...colorEntries.warning,
      DEFAULT: 'var(--dz-warning)',
      foreground: 'var(--dz-warning-foreground)',
    },
    danger: {
      ...colorEntries.danger,
      DEFAULT: 'var(--dz-danger)',
      foreground: 'var(--dz-danger-foreground)',
    },
    info: {
      ...colorEntries.info,
      DEFAULT: 'var(--dz-info)',
      foreground: 'var(--dz-info-foreground)',
    },
    accent: {
      DEFAULT: 'var(--dz-accent)',
      foreground: 'var(--dz-accent-foreground)',
    },
    card: {
      DEFAULT: 'var(--dz-card)',
      foreground: 'var(--dz-card-foreground)',
    },
    popover: {
      DEFAULT: 'var(--dz-popover)',
      foreground: 'var(--dz-popover-foreground)',
    },
    input: {
      DEFAULT: 'var(--dz-input-bg)',
      border: 'var(--dz-input-border)',
    },
  }

  // Add neutral palette shades
  if (colorEntries.neutral) {
    semanticColors.neutral = colorEntries.neutral
  }

  // Spacing entries
  const spacingEntries: Record<string, string> = {}
  for (const [key, value] of Object.entries(spacing)) {
    // --dz-spacing-{step} -> step
    const step = key.replace('--dz-spacing-', '').replace('_', '.')
    spacingEntries[step] = value
  }

  // Radius entries
  const radiusEntries: Record<string, string> = {}
  for (const [key, value] of Object.entries(radius)) {
    const step = key.replace('--dz-radius-', '')
    radiusEntries[step] = value
  }

  // Shadow entries
  const shadowEntries: Record<string, string> = {}
  for (const [key, value] of Object.entries(shadows)) {
    const step = key.replace('--dz-shadow-', '')
    shadowEntries[step] = value
  }

  const theme = {
    colors: semanticColors,
    spacing: spacingEntries,
    borderRadius: radiusEntries,
    boxShadow: shadowEntries,
  }

  return `/**
 * @dzup-ui/tokens — Tailwind CSS 4 Theme Extension
 *
 * DO NOT EDIT MANUALLY.
 * Generated by: yarn workspace @dzup-ui/tokens generate
 *
 * Usage in tailwind.config:
 *   import { dzTokens } from '@dzup-ui/tokens/tailwind'
 *   export default { theme: { extend: dzTokens } }
 *
 * Or with Tailwind CSS 4 @theme directive, import tokens.css directly.
 */

/** @type {import('tailwindcss').Config['theme']} */
export const dzTokens = ${JSON.stringify(theme, null, 2)};

export default dzTokens;
`
}

function generateTailwindThemeTypes(): string {
  return `/**
 * @dzup-ui/tokens — Tailwind Theme Type Definitions
 *
 * DO NOT EDIT MANUALLY.
 * Generated by: yarn workspace @dzup-ui/tokens generate
 */

import type { Config } from 'tailwindcss';

/** Tailwind theme extension with all dzup-ui design tokens */
export declare const dzTokens: NonNullable<Config['theme']>;
export default dzTokens;
`
}

// --------------------------------------------------------------------------
// Main
// --------------------------------------------------------------------------

function main(): void {
  mkdirSync(DIST_DIR, { recursive: true })

  const css = generateCss()
  const types = generateTypes()
  const tailwindTheme = generateTailwindTheme()
  const tailwindThemeTypes = generateTailwindThemeTypes()

  writeFileSync(resolve(DIST_DIR, 'tokens.css'), css, 'utf-8')
  writeFileSync(resolve(DIST_DIR, 'tokens.d.ts'), types, 'utf-8')
  writeFileSync(resolve(DIST_DIR, 'tailwind-theme.js'), tailwindTheme, 'utf-8')
  writeFileSync(resolve(DIST_DIR, 'tailwind-theme.d.ts'), tailwindThemeTypes, 'utf-8')

  const lineCount = css.split('\n').length
  const tokenCount = css.match(/--dz-/g)?.length ?? 0

  /* eslint-disable no-console */
  console.log('[tokens] Generated dist/tokens.css (%d lines, %d token declarations)', lineCount, tokenCount)
  console.log('[tokens] Generated dist/tokens.d.ts')
  console.log('[tokens] Generated dist/tailwind-theme.js')
  console.log('[tokens] Generated dist/tailwind-theme.d.ts')
  /* eslint-enable no-console */
}

main()
