/**
 * Central icon registry. Lucide icons are imported by name and exposed as a
 * record so data files can reference an icon by string key (keeps data.ts free
 * of component imports). Add an icon here before using its name in data.
 */
import type { Component } from 'vue'
import {
  Accessibility,
  Activity,
  Bell,
  Blocks,
  BookText,
  Boxes,
  Braces,
  Compass,
  Contact,
  CreditCard,
  Figma,
  FileSearch,
  FolderKanban,
  GitMerge,
  Headphones,
  LayoutDashboard,
  LayoutTemplate,
  LifeBuoy,
  LogIn,
  Megaphone,
  MoonStar,
  Newspaper,
  PackageCheck,
  Palette,
  PenLine,
  Rocket,
  Settings,
  Shapes,
  ShoppingCart,
  Sparkles,
  Store,
  SwatchBook,
  UserRound,
  Users,
  Wind,
  Wrench,
} from 'lucide-vue-next'

export const ICONS: Record<string, Component> = {
  Accessibility,
  Activity,
  Bell,
  Blocks,
  BookText,
  Boxes,
  Braces,
  Compass,
  Contact,
  CreditCard,
  Figma,
  FileSearch,
  FolderKanban,
  GitMerge,
  Headphones,
  LayoutDashboard,
  LayoutTemplate,
  LifeBuoy,
  LogIn,
  Megaphone,
  MoonStar,
  Newspaper,
  PackageCheck,
  Palette,
  PenLine,
  Rocket,
  Settings,
  Shapes,
  ShoppingCart,
  Sparkles,
  Store,
  SwatchBook,
  UserRound,
  Users,
  Wind,
  Wrench,
}
