/**
 * build-brand-assets — one-off generator for the landing's committed identity
 * assets (TASK-FREE-08). Everything here is authored as SVG and rasterised with
 * sharp, so the pixels are reproducible from this file alone:
 *
 *   • `public/favicon.svg`          — the brand mark (same artwork as the
 *                                     Storybook's `apps/storybook/public/favicon.svg`,
 *                                     kept byte-identical so the two apps share one
 *                                     identity).
 *   • `public/apple-touch-icon.png` — 180×180 PNG of the mark on its brand field.
 *   • `public/icon-192.png` / `public/icon-512.png` — web-manifest icons.
 *   • `public/site.webmanifest`     — minimal manifest naming the site + icons.
 *   • `public/og-default.png`       — the 1200×630 site-wide Open Graph card
 *                                     every route without its own share image
 *                                     inherits (referenced from index.html and
 *                                     `DEFAULT_HEAD` in src/router.ts).
 *
 * Run with `yarn brand-assets` (from apps/landing) and COMMIT the outputs — they
 * are stable identity assets, not per-build artifacts, so they are generated
 * once and only re-run when the brand changes. Colours are literal hex on
 * purpose: static images cannot reach the `--dz-*` tokens (primary-500 #0766ee,
 * same as the Storybook manager theme).
 */
import { Buffer } from 'node:buffer'
import { copyFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const __dirname = dirname(fileURLToPath(import.meta.url))
const LANDING_ROOT = resolve(__dirname, '..')
const PUBLIC_DIR = resolve(LANDING_ROOT, 'public')
const STORYBOOK_FAVICON = resolve(LANDING_ROOT, '..', 'storybook', 'public', 'favicon.svg')

/** The shared brand mark (mirrors favicon.svg), parameterised by canvas size. */
function markSvg(size: number): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 32 32">
  <rect width="32" height="32" rx="7" fill="#0766ee"/>
  <path d="M8 18.5 16 12l8 6.5" fill="none" stroke="#ffffff" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M8 23.5 16 17l8 6.5" fill="none" stroke="#ffffff" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" opacity="0.55"/>
</svg>`
}

/**
 * The site-wide OG card: brand mark + wordmark + tagline on a dark field with a
 * primary→violet accent band, 1200×630 (the canonical 1.91:1 share size).
 * Copy states no counts — counts drift (see build-counts.ts) and a committed
 * image cannot be regenerated by the claims spec, so the card stays count-free.
 */
const OG_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <defs>
    <linearGradient id="accent" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#0766ee"/>
      <stop offset="1" stop-color="#a855f7"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="630" fill="#0b1220"/>
  <rect x="0" y="622" width="1200" height="8" fill="url(#accent)"/>
  <g transform="translate(96 178) scale(3.4)">
    <rect width="32" height="32" rx="7" fill="#0766ee"/>
    <path d="M8 18.5 16 12l8 6.5" fill="none" stroke="#ffffff" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/>
    <path d="M8 23.5 16 17l8 6.5" fill="none" stroke="#ffffff" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" opacity="0.55"/>
  </g>
  <text x="238" y="258" font-family="Segoe UI, Arial, sans-serif" font-size="96" font-weight="700" fill="#f8fafc">dzup-ui</text>
  <text x="98" y="392" font-family="Segoe UI, Arial, sans-serif" font-size="44" font-weight="400" fill="#cbd5e1">The Vue 3 component library for serious products.</text>
  <text x="98" y="470" font-family="Segoe UI, Arial, sans-serif" font-size="30" font-weight="400" fill="#64748b">Accessible components · OKLCH design tokens · light &amp; dark out of the box</text>
</svg>`

const MANIFEST = {
  name: 'dzup-ui',
  short_name: 'dzup-ui',
  description: 'The Vue 3 component library for serious products.',
  start_url: '/',
  display: 'browser',
  background_color: '#0b1220',
  theme_color: '#0766ee',
  icons: [
    { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
  ],
}

async function main(): Promise<void> {
  // One identity across both apps: the landing favicon IS the Storybook favicon.
  await copyFile(STORYBOOK_FAVICON, resolve(PUBLIC_DIR, 'favicon.svg'))

  for (const [name, size] of [
    ['apple-touch-icon.png', 180],
    ['icon-192.png', 192],
    ['icon-512.png', 512],
  ] as const) {
    await sharp(Buffer.from(markSvg(size))).png().toFile(resolve(PUBLIC_DIR, name))
    console.log(`  ✓ ${name} (${size}×${size})`)
  }

  await sharp(Buffer.from(OG_SVG)).png({ compressionLevel: 9 }).toFile(resolve(PUBLIC_DIR, 'og-default.png'))
  console.log('  ✓ og-default.png (1200×630)')

  await writeFile(resolve(PUBLIC_DIR, 'site.webmanifest'), `${JSON.stringify(MANIFEST, null, 2)}\n`)
  console.log('  ✓ site.webmanifest')
}

main().catch((error: unknown) => {
  console.error(`✗ build-brand-assets failed: ${(error as Error).message}`)
  process.exitCode = 1
})
