/**
 * RTL contract validator and matrix generator (TASK-OSS-P4-05, ADR-19).
 *
 * Two jobs, one source of truth — the `rtl` field each component declares in
 * its anatomy:
 *
 *   1. **Gate.** A component that declares `mirrors: 'layout'` must not use
 *      physical `left`/`right` utilities in its variants. A physical utility is
 *      allowed only where the file says, in a comment, that it is deliberate.
 *   2. **Generate.** `packages/core/docs/rtl-matrix.md` is written from the
 *      manifest, so the table cannot drift from the declarations the way a
 *      hand-maintained one does.
 *
 * **What it does not check**: whether `margin-inline-start` actually resolves to
 * the right physical edge. That needs an engine that does layout, and it is
 * `expectRtlComputed` in the Playwright lane. A source check catches the
 * regression on the day it is written; the browser check catches the cases
 * source cannot see. Neither replaces the other, and this file claims only the
 * first.
 *
 * Usage:
 *   tsx packages/tooling/src/validators/rtl.ts            # check
 *   tsx packages/tooling/src/validators/rtl.ts --write    # regenerate the matrix
 *
 * Exit code 1 if a declaration and the source disagree, or the matrix is stale.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../')
const MANIFEST = resolve(ROOT, 'packages/core/manifests/component-ownership.manifest.json')
export const MATRIX_PATH = resolve(ROOT, 'packages/core/docs/rtl-matrix.md')

/**
 * Physical utilities that have a logical equivalent.
 *
 * Deliberately narrow. `rounded-lg`, `arrow-right` and `left-align-icon` are
 * not layout, and a rule that flagged them would be switched off within a week.
 */
const PHYSICAL
  = /(?:^|[\s'"`])-?(?:m[lr]|p[lr]|border-[lr]|rounded-[lr]|inset-[lr])-|(?:^|[\s'"`])text-(?:left|right)\b|(?:^|[\s'"`])-?border-[lr]\b/

/** The marker that declares a physical utility deliberate. */
const PHYSICAL_OK = 'rtl-physical-ok'

interface OwnershipEntry {
  symbol: string
  kind: string
  evidence?: string[]
  anatomy?: {
    riskTier: string
    rtl?: { mirrors: string, keyboard: string, icons?: string[] }
  }
}

export interface RtlViolation {
  symbol: string
  file: string
  line: number
  utility: string
}

/** The `.variants.ts` beside a component, if it has one. */
export function variantsFor(evidence: readonly string[] | undefined): string | undefined {
  const vue = evidence?.find(path => path.endsWith('.vue'))
  if (vue === undefined)
    return undefined
  const variants = vue.replace(/\.vue$/, '.variants.ts')
  return existsSync(resolve(ROOT, variants)) ? variants : undefined
}

/** Physical utilities in a variants source, minus the ones declared deliberate. */
export function physicalUtilitiesIn(source: string): { line: number, utility: string }[] {
  if (source.includes(PHYSICAL_OK))
    return []

  const found: { line: number, utility: string }[] = []
  source.split('\n').forEach((text, index) => {
    for (const match of text.matchAll(/[\w-]+/g)) {
      const token = match[0]
      if (PHYSICAL.test(` ${token}`))
        found.push({ line: index + 1, utility: token })
    }
  })
  return found
}

function entries(): OwnershipEntry[] {
  return (JSON.parse(readFileSync(MANIFEST, 'utf8')) as { entries: OwnershipEntry[] }).entries
}

export function checkRtlDeclarations(): RtlViolation[] {
  const violations: RtlViolation[] = []

  for (const entry of entries()) {
    const rtl = entry.anatomy?.rtl
    if (rtl === undefined || rtl.mirrors !== 'layout')
      continue

    const variants = variantsFor(entry.evidence)
    if (variants === undefined)
      continue

    for (const hit of physicalUtilitiesIn(readFileSync(resolve(ROOT, variants), 'utf8'))) {
      violations.push({ symbol: entry.symbol, file: variants, line: hit.line, utility: hit.utility })
    }
  }

  return violations
}

/** The matrix document, rendered from the manifest. */
export function renderMatrix(): string {
  const declared = entries()
    .filter(entry => entry.anatomy?.rtl !== undefined)
    .sort((a, b) => (a.symbol < b.symbol ? -1 : 1))

  const total = entries().filter(entry => entry.kind === 'public-component').length

  const rows = declared.map((entry) => {
    const rtl = entry.anatomy!.rtl!
    const icons = rtl.icons === undefined || rtl.icons.length === 0
      ? '—'
      : rtl.icons.map(i => `\`${i}\``).join(', ')
    return `| \`${entry.symbol}\` | ${rtl.mirrors} | ${rtl.keyboard} | ${icons} |`
  })

  return `<!-- AUTO-GENERATED by \`yarn generate:rtl-matrix\`. Do not edit. -->

# RTL semantics matrix

What each component does in a right-to-left document, as **declared** in its
\`Dz{Name}.anatomy.ts\` and checked by \`yarn validate:rtl\`.

Three axes, because they fail independently. A component can mirror its layout
correctly and still move the selection the wrong way on ArrowRight, and it can
get both right and still show a chevron pointing away from the panel it opens.

- **mirrors** — \`layout\` means margins, padding, borders and insets are
  logical, so the box flips with the document. \`none\` means the geometry is
  physical **on purpose**: source code, a media timeline, a side named by the
  author.
- **keyboard** — \`swap-horizontal\` means ArrowLeft and ArrowRight exchange
  meaning. Components that navigate the *block* axis (a listbox's ArrowUp and
  ArrowDown) declare \`none\`, because those keys do not swap.
- **icons** — parts whose icon carries direction and mirrors with the layout. A
  chevron pointing at the panel it opens is direction-bearing; a magnifying
  glass is not.

| Component | mirrors | keyboard | direction-bearing icons |
|---|---|---|---|
${rows.join('\n')}

**${declared.length} of ${total} public components declare an RTL contract.** The
rest are silent, not compliant: the field lives in the anatomy, and only
${declared.length} components declare an anatomy at all. The two rollouts are the
same rollout, ratcheted by \`maxWithoutAnatomy\` in
\`packages/tooling/src/ownership/unclassified-ceiling.json\`.

Components with **no** declaration are still covered by the repository-wide half
of this gate: \`yarn validate:rtl\` reports physical utilities for every
component that has declared \`mirrors: 'layout'\`, and the logical-property
migration in TASK-OSS-P4-05 converted the whole catalog's variants — 55 lines
across 26 files — regardless of whether the component had an anatomy yet.
`
}

/* c8 ignore start -- CLI entry point, exercised via `tsx`, not the unit tests. */
const isMain = process.argv[1]
  && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))

if (isMain) {
  const write = process.argv.includes('--write')
  const rendered = renderMatrix()

  if (write) {
    writeFileSync(MATRIX_PATH, rendered)
    console.warn(`✓ rtl-matrix → ${MATRIX_PATH.replace(`${ROOT}\\`, '').replace(`${ROOT}/`, '')}`)
  }

  const violations = checkRtlDeclarations()
  const stale = !existsSync(MATRIX_PATH) || readFileSync(MATRIX_PATH, 'utf8') !== rendered

  if (violations.length === 0 && !stale) {
    console.warn(
      `✓ rtl: every component declaring mirrors: 'layout' uses logical properties; `
      + 'the matrix matches the declarations.',
    )
    process.exit(0)
  }

  for (const v of violations) {
    console.error(
      `✗ ${v.symbol} declares mirrors: 'layout' but ${v.file}:${v.line} uses \`${v.utility}\`.`,
    )
  }
  if (stale) {
    console.error(
      '✗ packages/core/docs/rtl-matrix.md is stale. Run `yarn generate:rtl-matrix`.',
    )
  }
  process.exit(1)
}
/* c8 ignore stop */
