/**
 * RegistryClient — the single data layer behind every MCP tool.
 *
 * dzup-ui already generates a complete, shadcn-compatible catalog as STATIC
 * artifacts under the landing site's `public/` dir (see
 * `apps/landing/scripts/build-registry.ts` and `build-llms.mjs`):
 *
 *   /r/registry.json            — blocks index (shadcn `registry.json`)
 *   /r/<id>.json                — one block item, its SFC inlined in files[]
 *   /r/templates/registry.json  — templates index
 *   /r/templates/<id>.json      — one template item
 *   /r/tokens.json              — the --dz-* design tokens as light/dark cssVars
 *   /llms.txt, /llms-full.txt   — AI-readable BLOCKS docs (a different document)
 *   /storybook/llms.txt         — component API index (import path + taxonomy + props)
 *   /storybook/llms-full.txt    — full per-component props/emits/slots + usage
 *
 * Since TASK-N2-A3 the two `/storybook/llms*.txt` files are generated by
 * `yarn generate:llms` from `packages/core/docs/component-meta.json` and
 * committed at `packages/core/docs/llms{,-full}.txt`; `apps/storybook`'s
 * `build:llms` copies them into the site. They therefore cover ALL public
 * components, not the 101 that `public-api.manifest.json` exported.
 *
 * This client is a thin, cached reader over those files so the MCP server has
 * exactly ONE source of truth — the same bytes the website ships — rather than a
 * second, drifting copy of the catalog. It never mutates anything.
 *
 * Resolution modes (chosen from the base string):
 *   • `https://…`  — fetch over HTTP (production: the deployed site origin).
 *   • a local path — dev convenience: resolve `/storybook/*` under
 *     `apps/storybook/public` and everything else under `apps/landing/public`,
 *     relative to the repo root (falls back to `<base>/<path>` for a flat mirror).
 */

import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import process from 'node:process'

/** Default public origin serving the generated registry (registry.json `homepage`). */
export const DEFAULT_REGISTRY_URL = 'https://dzup-ui.com'

/**
 * Site path of the generated component-metadata artifact (TASK-N2-A2).
 *
 * ONE extraction, many renderers. `packages/core/docs/component-meta.json` is
 * produced by `yarn generate:component-meta`, which runs `vue-component-meta`
 * over the real `.vue`/`.types.ts` sources; the docs site, `llms-full.txt` and
 * the three metadata tools here all read it. Nothing in this package parses a
 * component source — that would be the second extractor the pipeline exists to
 * prevent.
 */
export const COMPONENT_META_PATH = '/r/component-meta.json'

/**
 * The shape every block/template id in the generated catalog actually has
 * (TASK-N2-A1).
 *
 * Measured, not invented: all 132 ids in `/r/registry.json` +
 * `/r/templates/registry.json` at `51dec93` match this exactly, longest 20
 * characters. It is a whitelist because of where these strings END UP —
 * `get_install_command` renders the id into a ```sh block containing a
 * `shadcn add <url>` line, and the server's own `instructions` tell the
 * assistant to hand that to the user. An id carrying a space produced a SECOND,
 * attacker-chosen registry URL inside the same command; see the TASK-N2-A1
 * handoff. Ids reach the tool from model context, which routinely includes
 * text the model merely read, so "it is only a name" is not a threat model.
 */
export const REGISTRY_ID_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

/** Generous vs. the measured maximum of 20 — a cap, not a schema. */
export const REGISTRY_ID_MAX_LENGTH = 64

/** True when `name` is a syntactically valid registry item id. */
export function isRegistryId(name: unknown): name is string {
  return typeof name === 'string'
    && name.length > 0
    && name.length <= REGISTRY_ID_MAX_LENGTH
    && REGISTRY_ID_RE.test(name)
}

/** A single item as it appears in a shadcn `registry.json` index. */
export interface RegistryIndexItem {
  name: string
  type: string
  title?: string
  description?: string
  categories?: string[]
  dependencies?: string[]
  registryDependencies?: string[]
  meta?: { components?: string[], tier?: string, [k: string]: unknown }
  files?: Array<{ path: string, type?: string, target?: string }>
}

/** A shadcn `registry.json` index (blocks or templates). */
export interface RegistryIndex {
  name: string
  homepage?: string
  items: RegistryIndexItem[]
}

/** A single resolved registry item (`/r/<id>.json`), SFC source inlined. */
export interface RegistryItem extends RegistryIndexItem {
  files?: Array<{ path: string, type?: string, target?: string, content?: string }>
}

/** The tokens theme item (`/r/tokens.json`). */
export interface TokensItem {
  name: string
  type: string
  title?: string
  description?: string
  cssVars?: { light?: Record<string, string>, dark?: Record<string, string> }
}

/** One component parsed out of the storybook `llms.txt` index. */
export interface ComponentSummary {
  name: string
  family: string
  description: string
  /** Raw follow-on lines from the index (props list, taxonomy) as a flat string. */
  details: string
}

// ── Component metadata (TASK-N2-A2) ─────────────────────────────────────────
//
// A structural mirror of the fields this package reads out of
// `packages/core/docs/component-meta.json`. Deliberately NOT the full generator
// type: `packages/tooling` may not be imported from a published package, and a
// published package must not depend on a private one. The artifact carries a
// `schemaVersion`, and `validate:component-meta` gates it against the sources,
// so a shape change is caught on the producing side.

/** One prop, as declared in the component's `.types.ts`. */
export interface MetaProp {
  name: string
  type: string
  required: boolean
  /** The DECLARED default. `null` = none declared; `"undefined"` = declared as `undefined`. */
  default: string | null
  description: string
  descriptionSource: string
  deprecated?: string
  examples?: string[]
}

/** One emitted event. */
export interface MetaEvent {
  name: string
  type: string
  signature: string
  description: string
  descriptionSource: string
  modelDerived: boolean
}

/** One slot. */
export interface MetaSlot {
  name: string
  type: string
  description: string
  descriptionSource: string
  hasPayload: boolean
}

/** One `defineExpose` member. */
export interface MetaExposed {
  name: string
  type: string
  description: string
  descriptionSource: string
}

/** One component's full metadata record. */
export interface ComponentMetaRecord {
  name: string
  kind: string
  parentComponent?: string
  family: string
  status?: string
  subpaths: string[]
  source: string
  typesSource?: string
  componentType: string
  tier?: string
  anatomy: { state: string, parts: string[], source?: string }
  capability?: {
    tier: string
    pattern: string
    securityBoundary: string
    traits: string[]
    cells: Record<string, number>
    unrun: string[]
    stale: string[]
  }
  props: MetaProp[]
  globalPropCount: number
  events: MetaEvent[]
  slots: MetaSlot[]
  exposed: MetaExposed[]
  stories: {
    file?: string
    titlePath?: string
    stories: { id: string, name?: string, lines: [number, number] }[]
    primary?: {
      id: string
      name?: string
      lines: [number, number]
      source: string
      template?: string
    }
  }
  extraction: Record<string, unknown>
  extractionError?: string
}

/** The whole component-metadata artifact. */
export interface ComponentMetaArtifact {
  schemaVersion: string
  sourceCommit: string
  extractor: string
  totals: Record<string, number>
  components: ComponentMetaRecord[]
}

/** Reader signature — `(sitePath) => contents`. Injectable for tests. */
export type Reader = (sitePath: string) => Promise<string>

/** True for an absolute http(s) base — HTTP mode; anything else is a local path. */
function isHttp(base: string): boolean {
  return /^https?:\/\//i.test(base)
}

/**
 * Build the default reader for a base. HTTP bases fetch; local bases map site
 * paths onto the two `public/` dirs of the monorepo (see file header).
 */
export function createReader(base: string): Reader {
  if (isHttp(base)) {
    const origin = base.replace(/\/+$/, '')
    return async (sitePath) => {
      const url = `${origin}${sitePath}`
      const res = await fetch(url)
      if (!res.ok)
        throw new Error(`GET ${url} → ${res.status} ${res.statusText}`)
      return res.text()
    }
  }
  // Local dev mode: <repoRoot>/apps/{landing,storybook}/public mirror the site.
  const root = base.replace(/[/\\]+$/, '')
  return async (sitePath) => {
    const rel = sitePath.replace(/^\//, '')
    const candidates = rel.startsWith('storybook/')
      ? [
          join(root, 'apps/storybook/public', rel.slice('storybook/'.length)),
          // The component-API llms docs are generated into packages/core/docs
          // and COPIED into apps/storybook/public by that app's `build:llms`.
          // The copy is git-ignored, so in a fresh clone it is absent while the
          // committed source of truth is present — resolve to it rather than
          // reporting a component catalog that exists on disk as missing.
          // Same shape as the component-meta fallback below. TASK-N2-A3;
          // `validate:llms` asserts the production copy step still exists.
          ...(sitePath === '/storybook/llms.txt'
            ? [join(root, 'packages/core/docs/llms.txt')]
            : []),
          ...(sitePath === '/storybook/llms-full.txt'
            ? [join(root, 'packages/core/docs/llms-full.txt')]
            : []),
          join(root, sitePath),
        ]
      : [
          join(root, 'apps/landing/public', rel),
          // The component-metadata artifact is generated into packages/core/docs
          // and COPIED into apps/landing/public/r by the landing registry build
          // (which wipes that directory on every run). In a checkout where the
          // landing build has not been run, the copy is absent while the source
          // of truth is committed and present — so a local base resolves to it
          // directly rather than reporting a component catalog that exists on
          // disk as missing. TASK-N2-A2; `validate:component-meta` asserts the
          // production copy step still exists.
          ...(sitePath === COMPONENT_META_PATH
            ? [join(root, 'packages/core/docs/component-meta.json')]
            : []),
          join(root, sitePath),
        ]
    let lastErr: unknown
    for (const p of candidates) {
      try {
        return await readFile(p, 'utf8')
      }
      catch (err) {
        lastErr = err
      }
    }
    throw lastErr instanceof Error ? lastErr : new Error(`Cannot read ${sitePath}`)
  }
}

export interface RegistryClientOptions {
  /** Origin URL or local path. Defaults to $DZUP_UI_REGISTRY_URL or the public site. */
  base?: string
  /** Override the reader entirely (tests). Takes precedence over `base`. */
  reader?: Reader
}

/**
 * Cached, read-only accessor for the dzup-ui catalog artifacts. One instance is
 * shared by every tool; each distinct site path is fetched at most once per
 * process (the artifacts are immutable per deploy).
 */
export class RegistryClient {
  readonly base: string
  private readonly read: Reader
  private readonly cache = new Map<string, Promise<string>>()

  constructor(opts: RegistryClientOptions = {}) {
    this.base = opts.base ?? process.env.DZUP_UI_REGISTRY_URL ?? DEFAULT_REGISTRY_URL
    this.read = opts.reader ?? createReader(this.base)
  }

  /** The public origin used to build install-command URLs (http mode) or the site default. */
  get origin(): string {
    return isHttp(this.base) ? this.base.replace(/\/+$/, '') : DEFAULT_REGISTRY_URL
  }

  private text(sitePath: string): Promise<string> {
    let hit = this.cache.get(sitePath)
    if (!hit) {
      hit = this.read(sitePath)
      this.cache.set(sitePath, hit)
    }
    return hit
  }

  private async json<T>(sitePath: string): Promise<T> {
    return JSON.parse(await this.text(sitePath)) as T
  }

  // ── Blocks ────────────────────────────────────────────────────────────────

  blocksIndex(): Promise<RegistryIndex> {
    return this.json<RegistryIndex>('/r/registry.json')
  }

  block(name: string): Promise<RegistryItem> {
    return this.json<RegistryItem>(`/r/${encodeURIComponent(name)}.json`)
  }

  /**
   * Absolute URL a consumer's `shadcn add` fetches for a block.
   *
   * Encoded, like `block()` above. The two used to disagree: `block()` encoded
   * and this did not, so the item that was fetched and the URL that was printed
   * could differ for the same argument.
   */
  blockUrl(name: string): string {
    return `${this.origin}/r/${encodeURIComponent(name)}.json`
  }

  // ── Templates ───────────────────────────────────────────────────────────────

  templatesIndex(): Promise<RegistryIndex> {
    return this.json<RegistryIndex>('/r/templates/registry.json')
  }

  template(name: string): Promise<RegistryItem> {
    return this.json<RegistryItem>(`/r/templates/${encodeURIComponent(name)}.json`)
  }

  /** Absolute URL a consumer's `shadcn add` fetches for a template. Encoded, see `blockUrl`. */
  templateUrl(name: string): string {
    return `${this.origin}/r/templates/${encodeURIComponent(name)}.json`
  }

  // ── Tokens ────────────────────────────────────────────────────────────────

  tokens(): Promise<TokensItem> {
    return this.json<TokensItem>('/r/tokens.json')
  }

  tokensUrl(): string {
    return `${this.origin}/r/tokens.json`
  }

  // ── Components (parsed from the storybook llms docs) ──────────────────────────

  /** The component API index markdown (`/storybook/llms.txt`). */
  componentsIndexText(): Promise<string> {
    return this.text('/storybook/llms.txt')
  }

  /** The full per-component API markdown (`/storybook/llms-full.txt`). */
  componentsFullText(): Promise<string> {
    return this.text('/storybook/llms-full.txt')
  }

  async components(): Promise<ComponentSummary[]> {
    return parseComponentIndex(await this.componentsIndexText())
  }

  /** The full markdown section for one component, or null if not found. */
  async component(name: string): Promise<string | null> {
    return extractComponentSection(await this.componentsFullText(), name)
  }

  // ── Component metadata (TASK-N2-A2) ───────────────────────────────────────

  /**
   * The generated component-metadata artifact — every component's
   * props/slots/emits/exposed extracted from source by `vue-component-meta`,
   * joined to family/tier/anatomy/capability state and to real story source.
   *
   * One read, cached like every other artifact. Extraction happens at
   * generate-time and is never on the serve path.
   */
  componentMeta(): Promise<ComponentMetaArtifact> {
    return this.json<ComponentMetaArtifact>(COMPONENT_META_PATH)
  }

  /** One component's record by name (`Dz`-prefix optional, case-insensitive), or null. */
  async componentMetaFor(name: string): Promise<ComponentMetaRecord | null> {
    const wanted = normalizeComponentName(name)
    const artifact = await this.componentMeta()
    return artifact.components.find(c => normalizeComponentName(c.name) === wanted) ?? null
  }
}

/**
 * Parse the storybook `llms.txt` index into a flat component list.
 *
 * The index groups components under `## <Family>` headers; each component is a
 * `- **Name** — description` bullet followed by indented `  - …` detail lines
 * (props list, taxonomy). The leading `## Conventions` section is not a family
 * and is skipped.
 *
 * The component-name pattern is `[A-Z][A-Za-z0-9]*`, not `Dz[A-Za-z0-9]+`.
 * TASK-N2-A2 finding F-5 measured **two public components that are not
 * `Dz`-prefixed** — `GovernanceBadge` and `TeamMemberBadge` — and the narrower
 * pattern made them unparseable even once they were present in the index, so
 * `list_components` and `get_component` could not see them. `normalizeComponentName`
 * already handles both forms identically, so only the pattern had to change.
 * Safe because the only bold-led bullets in this document sit under a family
 * heading; the curated `## Conventions` section is skipped by name, and
 * `validate:llms` re-parses the generated file with this same expectation.
 */
export function parseComponentIndex(md: string): ComponentSummary[] {
  const out: ComponentSummary[] = []
  const lines = md.split(/\r?\n/)
  let family = ''
  let current: ComponentSummary | null = null
  const flush = () => {
    if (current) {
      current.details = current.details.trim()
      out.push(current)
      current = null
    }
  }
  for (const line of lines) {
    const fam = /^##\s+(\S.*)$/.exec(line)
    if (fam) {
      flush()
      family = fam[1]!.trim()
      continue
    }
    if (family === 'Conventions' || !family)
      continue
    // `- **Name** — description`  (em dash or hyphen separator, both tolerated)
    const head = /^-\s+\*\*([A-Z][A-Za-z0-9]*)\*\*(.*)$/.exec(line)
    if (head) {
      flush()
      const description = head[2]!.trim().replace(/^[—–-]\s*/, '')
      current = { name: head[1]!, family, description, details: '' }
      continue
    }
    // Indented continuation line belongs to the component currently being read.
    if (current && /^\s+-\s+/.test(line)) {
      current.details += `${line.trim().replace(/^-\s+/, '')}\n`
    }
  }
  flush()
  return out
}

/**
 * Slice the full markdown section for a single component out of
 * `llms-full.txt`. Sections are delimited by `### Name` headers and run until
 * the next `### ` or `## ` header. Case-insensitive, `Dz`-prefix tolerant, and
 * — since TASK-N2-A3 — tolerant of the two public components that carry no
 * `Dz` prefix at all (see `parseComponentIndex`).
 */
export function extractComponentSection(md: string, name: string): string | null {
  const wanted = normalizeComponentName(name)
  const lines = md.split(/\r?\n/)
  let start = -1
  for (let i = 0; i < lines.length; i++) {
    const m = /^###\s+([A-Z][A-Za-z0-9]*)\s*$/.exec(lines[i]!)
    if (m && normalizeComponentName(m[1]!) === wanted) {
      start = i
      break
    }
  }
  if (start === -1)
    return null
  let end = lines.length
  for (let i = start + 1; i < lines.length; i++) {
    if (/^###?\s+/.test(lines[i]!)) {
      end = i
      break
    }
  }
  return lines.slice(start, end).join('\n').trim()
}

/** Canonicalize a component name to `dzbutton` form (Dz-prefixed, lowercased). */
export function normalizeComponentName(name: string): string {
  const trimmed = name.trim()
  const prefixed = /^dz/i.test(trimmed) ? trimmed : `Dz${trimmed}`
  return prefixed.toLowerCase()
}
