/**
 * Commercial templates, as metadata only (docs/templates.md §9, decision T-D06).
 *
 * The commercial templates live in the private dzup-templates repository and are
 * previewed in its showroom. This MIT gallery may say that they exist, and link
 * to them, but must never import their code. So it reads a public-safe snapshot
 * generated by dzup-templates (`yarn write:landing-snapshot` there), the same way
 * `data.ts` reads the Pro showcase snapshot.
 *
 * The snapshot is optional: `import.meta.glob` yields an empty record when the
 * file is absent, so the free build stays green without it. These rows are
 * deliberately NOT part of `TEMPLATES`: they have no render, no source and no
 * `/r/templates/<slug>.json` registry item.
 */

export interface CommercialTemplate {
  slug: string
  name: string
  blurb: string
  category: string
  tags: string[]
  stack: string[]
  /** Commercial tier: 'H' (Core-only, commercial licence) or 'P' (needs Pro). */
  tier: string
  licence: string
  createdAt: string
  /** Showroom detail page. */
  detailUrl: string
  /** Showroom chromeless live preview. */
  previewUrl: string
  thumbnail: { light: string, dark: string }
}

export interface CommercialSnapshot {
  schemaVersion: 1
  showroomUrl: string
  templates: CommercialTemplate[]
}

const snapshotModules = import.meta.glob<CommercialSnapshot>(
  '../generated/commercial-templates.snapshot.json',
  { eager: true, import: 'default' },
)

function isHttpsUrl(value: unknown): value is string {
  if (typeof value !== 'string')
    return false
  try {
    return new URL(value).protocol === 'https:'
  }
  catch {
    return false
  }
}

function isStringList(value: unknown): value is string[] {
  return Array.isArray(value) && value.every(item => typeof item === 'string')
}

function isCommercialTemplate(row: unknown): row is CommercialTemplate {
  if (typeof row !== 'object' || row === null)
    return false
  const r = row as Record<string, unknown>
  const thumb = r.thumbnail as Record<string, unknown> | undefined
  return typeof r.slug === 'string' && /^[a-z0-9-]+$/.test(r.slug)
    && typeof r.name === 'string'
    && typeof r.blurb === 'string'
    && typeof r.category === 'string'
    && isStringList(r.tags)
    && isStringList(r.stack)
    && typeof r.tier === 'string'
    && typeof r.licence === 'string' && r.licence !== 'mit'
    && typeof r.createdAt === 'string'
    && isHttpsUrl(r.detailUrl)
    && isHttpsUrl(r.previewUrl)
    && typeof thumb === 'object' && thumb !== null
    && isHttpsUrl(thumb.light) && isHttpsUrl(thumb.dark)
}

/**
 * Read the snapshot modules. An absent file, a wrong schema version or a
 * malformed row yields fewer rows, never a crash: the free gallery must render
 * whatever state the optional snapshot is in.
 */
export function commercialTemplatesFrom(modules: Record<string, unknown>): CommercialTemplate[] {
  const snapshot = Object.values(modules)[0] as Partial<CommercialSnapshot> | undefined
  if (!snapshot || snapshot.schemaVersion !== 1 || !Array.isArray(snapshot.templates))
    return []
  return snapshot.templates.filter(isCommercialTemplate)
}

export const COMMERCIAL_TEMPLATES: CommercialTemplate[] = commercialTemplatesFrom(snapshotModules)

/** Badge copy for a commercial tier. */
export function commercialTierLabel(t: CommercialTemplate): string {
  return t.tier === 'P' ? 'Commercial · Pro' : 'Commercial'
}
