/**
 * The docs site's page renderer (TASK-N2-D1).
 *
 * Pure functions: artifact in, markdown out. No filesystem, no `.vue`, no
 * `.types.ts`, no TypeScript program — constraint **B9** makes
 * `packages/core/docs/component-meta.json` the single component-API extraction
 * in this repository, and a docs app that parsed a component source would be
 * the second one.
 *
 * ## This is NOT a second renderer
 *
 * The body of every component page is
 * {@link renderComponentSection | `renderComponentSection`} from
 * `../llms/render-llms.ts` — literally the function `llms-full.txt` is built
 * from, called with `{ level: 1, memberHeadingLevel: 2 }`. The N2-A3 handoff
 * §14 handed that seam forward and asked for exactly this: a `level` parameter
 * on the existing function rather than a copy of it, "because it keeps the
 * shape in one place". So the three rules an API renderer must not get wrong —
 * declared-vs-effective defaults, `descriptionSource`, verbatim-or-absent
 * examples — are implemented once, and this file cannot drift from
 * `llms-full.txt` because it *is* `llms-full.txt`'s renderer.
 *
 * What this module adds is everything a *page* needs that a section does not:
 * front matter, family/kind provenance, the "how to read this page" contract,
 * the merge point for hand-written usage prose, the compound parts nested under
 * their parent, and a per-page extraction-fidelity block.
 *
 * ## Why the fidelity block exists
 *
 * README §3 `<evidence_rules>`: *stale/unrun cells stay visible*. A prop table
 * that renders 12 rows and says nothing else invites the reader to conclude the
 * component is fully documented. Publishing the per-component measurements
 * beside the table — how many descriptions exist, how many defaults are
 * declared `undefined`, where event prose came from, that no `defineExpose`
 * member anywhere in the catalog has a description — is the same argument the
 * N1 lane makes about evidence generally, applied to documentation.
 *
 * ## Vue-safety
 *
 * VitePress compiles markdown to a Vue SFC, so a bare `<span>` in a prop
 * description (53 members in the catalog carry angle brackets) would be parsed
 * as a component and can break the build. {@link escapeForVue} escapes `<` and
 * `{{` outside fenced blocks and outside inline code spans, where markdown-it
 * has not already escaped them.
 *
 * @module @dzup-ui/tooling/docs/docs-pages
 */

import type { ComponentMetaArtifact, ComponentMetaRecord } from '../meta/component-meta.ts'
import type { SeedRefusal } from '../playground/playground-contract.ts'
import type { EvidenceSources } from './evidence.ts'
import { FAMILY_LABELS, FAMILY_ORDER } from '../llms/llms-content.ts'
import { groupByFamily, renderComponentSection } from '../llms/render-llms.ts'
import { renderEvidence } from './evidence.ts'

/** Directory (relative to the docs app root) the generated component pages live in. */
export const COMPONENTS_DIR = 'components'
/** Directory holding hand-written per-component prose the generator merges. */
export const USAGE_DIR = 'components/_usage'

/** The banner every generated file carries, so nobody edits one by accident. */
export const GENERATED_BANNER
  = '<!-- GENERATED by `yarn generate:docs-pages` from packages/core/docs/component-meta.json.\n'
    + '     Every API fact on this page is a projection of that artifact (constraint B9); edits are\n'
    + '     overwritten on the next run. Hand-written prose belongs in components/_usage/<Name>.md. -->'

/**
 * The contract note printed on every component page.
 *
 * These are the N2-A2 handoff §13 rules, stated to the reader instead of being
 * silently obeyed. A reader who does not know that `undefined` in the default
 * column is a *declared* value has been misinformed by a technically-correct
 * table.
 */
export const HOW_TO_READ: readonly string[] = [
  '::: info How to read the tables on this page',
  'Everything below is extracted from source by `vue-component-meta` and published as measured,',
  'never as asserted.',
  '',
  '- **Declared default** is what the component *declares*, not what you necessarily get. Many props',
  '  declare `undefined` on purpose so the surrounding `DzProvider` supplies the effective value at',
  '  runtime (ADR-20). `—` means no default is declared at all; those are different facts and are not',
  '  collapsed here.',
  '- **An empty description cell (`—`) means no prose exists in source**, not that the member is',
  '  self-explanatory. The per-page counts under *Extraction fidelity* say how many are in that state.',
  '- **Event descriptions are recovered from the `Dz*Emits` interface**, because Vue\'s `ShortEmits`',
  '  mapped type erases the JSDoc before any extractor can see it. Events written by `defineModel`',
  '  (ADR-16) have no authored description anywhere and say so.',
  '- **`defineExpose` members are published as names and types only.** No description exists in',
  '  source for any of them, catalog-wide, so the column is omitted rather than shown empty.',
  '- **Usage snippets are verbatim slices of the component\'s Storybook story.** Nothing on this site',
  '  synthesises example markup; a component without a story says so.',
  ':::',
] as const

// ── Vue-safety ──────────────────────────────────────────────────────────────

/**
 * Escape one run of text that markdown-it will emit as raw HTML.
 *
 * `<` becomes `&lt;` so a description mentioning `<span>` renders as text
 * instead of being compiled as a component; `{{` is escaped so a description
 * containing a mustache cannot become an interpolation. Existing entities are
 * left alone (`&` is not touched), because the inputs are JSDoc prose and
 * TypeScript type strings, neither of which contains entity syntax.
 */
export function escapeVueText(text: string): string {
  return text.replace(/</g, '&lt;').replace(/\{\{/g, '&#123;&#123;')
}

/**
 * The only component tags a generated page may open — TASK-N2-D3.
 *
 * D1 §15 gave D3 two options and forbade the third: *"D3 must add its component
 * tags to an allowlist (or push them through a channel the escaper skips) — and
 * must **not** simply disable the escaper, or `DzBreadcrumb.md` breaks the build
 * again."* This is that allowlist, and it is deliberately a closed set of exact
 * names rather than a pattern: a pattern like `Dz[A-Z]` would also un-escape
 * every `<DzButton …>` a **prop description** happens to contain, which is
 * precisely the class of defect (D1 F-1) the escaper exists to stop. There are
 * 12 descriptions carrying raw HTML in the catalogue today and the escaper is
 * the only thing standing between them and a failed build.
 */
export const ALLOWED_PAGE_COMPONENTS = ['DzPlayground'] as const

/**
 * A line that is entirely one allowlisted component tag, on its own.
 *
 * Anchored at both ends so the tag can only be the whole line — a description
 * that mentions `<DzPlayground>` mid-sentence stays escaped.
 */
// The non-capturing group is redundant only while the allowlist has exactly one
// entry. Removing it would make `^<A|B(?:\s…)?/>$` mean something else entirely
// the moment a second tag is allowed, so it stays and the rule is silenced here.
const ALLOWED_TAG_LINE = new RegExp(
  // eslint-disable-next-line regexp/no-useless-non-capturing-group
  `^<(?:${ALLOWED_PAGE_COMPONENTS.join('|')})(?:\\s[^<>]*)?/>$`,
)

/**
 * True when a line is exactly one allowlisted component tag.
 *
 * Exported so the whole-catalogue "no unescaped markup" assertion in
 * `docs-pages.spec.ts` asks this function rather than carrying its own copy of
 * the allowlist. That assertion failed the moment the playground tag started
 * being emitted (D3-F6): the test's rule and the escaper's rule were the same
 * rule stated twice, and only one of them was updated.
 */
export function isAllowedComponentLine(line: string): boolean {
  return ALLOWED_TAG_LINE.test(line.trim())
}

/**
 * Apply {@link escapeVueText} to a rendered page, skipping fenced code blocks
 * and inline code spans — markdown-it already escapes both, and injecting
 * entities there would make them visible as literal `&lt;`.
 *
 * Fence tracking follows CommonMark: a fence closes on a run of the same
 * character at least as long as the opener, which is the rule
 * `render-llms.ts`'s `fenceFor` relies on when it widens a fence around a
 * snippet that itself contains backticks.
 */
export function escapeForVue(lines: readonly string[]): string[] {
  const out: string[] = []
  let openFence: string | null = null
  let inComment = false
  // Split on real newlines first. `render-llms.ts`'s `fenced()` returns a whole
  // fenced block — opener, body and closer — as ONE array element, so a tracker
  // that only inspected elements would open a fence and never see it close, and
  // would then treat the entire rest of the page as code. That is not
  // hypothetical: it was the first VitePress build failure of this packet
  // (`DzBreadcrumb.md`, "Element is missing end tag" on an unescaped `<span>` in
  // a prop description that sat after the usage snippet).
  for (const line of lines.flatMap(l => l.split('\n'))) {
    const fence = /^(\s*)([`~]{3,})/.exec(line)
    if (openFence !== null) {
      out.push(line)
      if (fence !== null && fence[2]!.startsWith(openFence[0]!) && fence[2]!.length >= openFence.length)
        openFence = null
      continue
    }
    if (fence !== null) {
      openFence = fence[2]!
      out.push(line)
      continue
    }
    // HTML comments pass through unescaped. They are inert in a Vue template,
    // and escaping the `<!--` turns an invisible authoring note into visible
    // page text — which is what the first generated `DzAccordion.md` did.
    if (inComment) {
      out.push(line)
      if (line.includes('-->'))
        inComment = false
      continue
    }
    if (line.trimStart().startsWith('<!--')) {
      out.push(line)
      if (!line.includes('-->'))
        inComment = true
      continue
    }
    // A whole-line, self-closing tag from the closed allowlist passes through
    // unescaped — the ONE channel by which this generator may emit a component
    // (TASK-N2-D3, D1 §15). Everything else, including the same name inside
    // prose, is still escaped by the branch below.
    if (isAllowedComponentLine(line)) {
      out.push(line)
      continue
    }
    // Outside a fence: split on inline-code spans and escape only the gaps.
    const segments = line.split('`')
    out.push(segments.map((seg, i) => (i % 2 === 1 ? seg : escapeVueText(seg))).join('`'))
  }
  return out
}

// ── Small helpers ───────────────────────────────────────────────────────────

/**
 * Drop HTML comment blocks from hand-written prose before it is merged.
 *
 * Each `components/_usage/<Name>.md` opens with an authoring guard-rail — "prose
 * only, do not write a table here". That note is addressed to whoever edits the
 * file, not to a reader of the site, and carrying it onto the page would publish
 * repository instructions as documentation.
 */
export function stripHtmlComments(text: string): string {
  return text.replace(/<!--[\s\S]*?-->/g, '')
}

/** A YAML double-quoted scalar. Front matter is data, so it is quoted, not guessed at. */
export function yamlString(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/** Human label for a family key; falls back to the key so an unlabelled family is visible, not hidden. */
export function familyLabel(key: string): string {
  return FAMILY_LABELS[key] ?? key
}

/** Curated family order first, then anything new, alphabetically. */
export function orderedFamilies(artifact: ComponentMetaArtifact): string[] {
  const present = new Set(artifact.components.map(c => c.family))
  return [
    ...FAMILY_ORDER.filter(k => present.has(k)),
    ...[...present].filter(k => !FAMILY_ORDER.includes(k)).sort((a, b) => a.localeCompare(b, 'en')),
  ]
}

/** Public components only, in the same family/name order the whole site uses. */
export function publicComponents(artifact: ComponentMetaArtifact): ComponentMetaRecord[] {
  return groupByFamily(artifact.components.filter(c => c.kind === 'public-component'))
    .flatMap(g => g.components)
}

/** The compound parts belonging to a component, name-sorted. */
export function compoundPartsOf(
  record: ComponentMetaRecord,
  artifact: ComponentMetaArtifact,
): ComponentMetaRecord[] {
  return artifact.components
    .filter(c => c.kind === 'compound-part' && c.parentComponent === record.name)
    .sort((a, b) => a.name.localeCompare(b.name, 'en'))
}

/**
 * Split a rendered component section into `[heading…, metaBullets, rest]`.
 *
 * The meta block is the contiguous run of `- ` bullets that
 * `renderComponentSection` always opens with `- **Install:**`. Splitting on that
 * function's own output rather than re-deriving it keeps the page assembly here
 * and the section shape there, which is the point of reusing the function.
 */
export function splitSection(lines: readonly string[]): {
  head: string[]
  meta: string[]
  rest: string[]
} {
  const start = lines.findIndex(l => l.startsWith('- **Install:**'))
  if (start === -1)
    return { head: [...lines], meta: [], rest: [] }
  let end = start
  while (end < lines.length && lines[end]!.startsWith('- '))
    end += 1
  return {
    head: lines.slice(0, start),
    meta: lines.slice(start, end),
    rest: lines.slice(end),
  }
}

// ── The per-page fidelity block ─────────────────────────────────────────────

/**
 * The measured extraction quality for one component, rendered as a table.
 *
 * Every number is read out of `record.extraction`, which the A2 pipeline
 * publishes per component precisely so a renderer can show it. A row is shown
 * for a member kind with zero members too — "0 events" and "we could not read
 * the events" are different claims, and the notes column says which one applies.
 */
export function renderFidelity(record: ComponentMetaRecord): string[] {
  const x = record.extraction
  const undefinedDefaults = record.props.filter(p => p.default === 'undefined').length
  const fromEmits = record.events.filter(e => e.descriptionSource === 'emits-interface').length
  const modelDerived = record.events.filter(e => e.modelDerived).length

  /**
   * True when the component declares an API in source and the extractor
   * recovered none of it.
   *
   * Every "0" in the table below then means **unknown**, not **none**, and the
   * Notes column has to say so. Writing "the component emits nothing" for
   * `DzAccordion` would be the exact failure this whole page argues against:
   * a zero that reads as a measurement when it is an absence of one.
   */
  const gap = record.typesSource !== undefined
    && record.props.length === 0 && record.events.length === 0 && record.slots.length === 0
  const unknown = 'unknown — the extractor recovered nothing for this component (see below)'

  const rows: string[][] = [
    ['Props', String(x.props), String(x.propsWithDescription), gap
      ? unknown
      : undefinedDefaults === 0
        ? `${x.propsWithDeclaredDefault} declare a default`
        : `${x.propsWithDeclaredDefault} declare a default, of which ${undefinedDefaults} declare \`undefined\` (ADR-20 provider supplies the value)`],
    ['Events', String(x.events), String(x.eventsWithDescription), gap
      ? unknown
      : x.events === 0
        ? 'the component emits nothing'
        : `${fromEmits} recovered from the \`Dz*Emits\` interface · ${modelDerived} synthesised by \`defineModel\``],
    ['Slots', String(x.slots), String(x.slotsWithDescription), gap
      ? unknown
      : x.slots === 0
        ? 'the component declares no slots'
        : `${x.slotsWithPayload} carry slot props`],
    ['Exposed on `ref`', String(x.exposed), String(x.exposedWithDescription), gap
      ? unknown
      : x.exposed === 0
        ? 'nothing is exposed on the template ref'
        : 'no description exists in source for any exposed member, catalog-wide'],
  ]

  const lines = [
    '## Extraction fidelity',
    '',
    'Published rather than assumed. These are this component\'s own numbers, measured by the',
    'extraction that produced the tables above.',
    '',
    '| Member kind | Extracted | With a description | Notes |',
    '| --- | --- | --- | --- |',
    ...rows.map(r => `| ${r.join(' | ')} |`),
    '',
  ]

  if (x.unresolvedTypes.length > 0) {
    lines.push(
      `**${x.unresolvedTypes.length} member type(s) could not be resolved** and are printed as the`,
      `extractor left them: ${x.unresolvedTypes.map(t => `\`${t}\``).join(', ')}.`,
      '',
    )
  }

  if (record.props.length === 0 && record.events.length === 0 && record.slots.length === 0) {
    lines.push(
      record.typesSource === undefined
        ? '::: tip Nothing to extract\nThis component declares no API in source, so the absence above is the whole truth.\n:::'
        : '::: danger Extraction gap — do not read the absence above as an empty API\n'
          + `\`${record.name}\` declares its API in \`${record.typesSource}\`, yet the extractor recovered `
          + 'no props, events or slots from it. **This page cannot tell you what the component accepts.** '
          + 'Read the types file. This is tracked as a downward-only ratchet so a second component '
          + 'cannot enter this state unnoticed.\n:::',
      '',
    )
  }

  if (record.stories.primary === undefined && record.kind === 'public-component') {
    lines.push(
      '::: warning No published example\n'
      + 'No Storybook story exists for this component, so no usage snippet is shown. This site never '
      + 'synthesises example markup.\n:::',
      '',
    )
  }

  return lines
}

// ── The component page ──────────────────────────────────────────────────────

/** Inputs a component page needs beyond the artifact itself. */
// ── The playground section (TASK-N2-D3) ─────────────────────────────────────

/**
 * The *Playground* section of a component page.
 *
 * Two shapes, and only two. Either the component has a story whose static
 * template stands alone outside Storybook — in which case the page emits the
 * one allowlisted tag and the seed is looked up at runtime from
 * `public/playground/seeds.json` — or it has none, in which case the page says
 * so in a sentence and emits **nothing**.
 *
 * There is no third shape. The task says twice that a playground must run real
 * story code and never synthesised markup, and **15 of 144** public components
 * have no story that qualifies (D3-F1). Those 15 get the honest absence, in the
 * same register D1 uses for `DzThemeProvider`'s missing example and D2 uses for
 * the `unrun` capability cells.
 *
 * **The absence states the MEASURED reason**, carried here as a `SeedRefusal`
 * from the one place that decides. It did not always: the first implementation
 * of this section composed a plausible sentence at render time, and on three
 * pages that sentence was false (D3-F5). A reason a page infers is a metric a
 * page hand-types.
 *
 * The seed is NOT inlined into the markdown, deliberately. Every byte written
 * here lands in the page, in the 20.67 MB static build **and in the offline
 * search index** — D2's F-10 measured that index doubling to 1.54 MB because
 * evidence headings are indexed, and 144 SFC seeds would be the next such
 * doubling for content no reader searches for.
 */
/**
 * The one sentence a page prints in place of a playground.
 *
 * Exhaustive over `SeedRefusalReason` with no `default:` branch, so a new
 * refusal reason is a compile error here rather than a silently generic
 * sentence — which is how the three false sentences got published.
 */
export function refusalSentence(refusal: SeedRefusal): string {
  const file = refusal.file === undefined ? 'its stories file' : `\`${refusal.file}\``
  switch (refusal.reason) {
    case 'no-stories-file':
      return 'It has no stories file, so there is no real example to run — and this page will not '
        + 'invent one.'
    case 'no-runnable-story':
      return `Every story in ${file} either has a computed template or binds Storybook's \`args\`, `
        + 'neither of which can be mounted outside Storybook. A playground here would have to be '
        + 'written by hand, and a hand-written example is not evidence of anything.'
    case 'no-component-tag':
      return `The runnable story in ${file} opens no component tag, so a sandbox seeded from it `
        + 'would render an empty box rather than this component.'
    case 'unexported-tags': {
      const tags = refusal.tags ?? []
      const named = tags.map(t => `\`<${t}>\``)
      const list = named.length < 2 ? named.join('') : `${named.slice(0, -1).join(', ')} and ${named.at(-1)}`
      const one = named.length === 1
      return `The runnable story in ${file} opens ${list}, which \`@dzup-ui/core\` does not `
        + `export — ${one ? 'it is' : 'they are'} defined inside the story file itself. A sandbox `
        + `cannot import ${one ? 'it' : 'them'}, and substituting something else would be inventing `
        + 'the example.'
    }
  }
}

export function renderPlayground(
  record: ComponentMetaRecord,
  hasSeed?: boolean,
  refusal?: SeedRefusal,
): string[] {
  if (record.kind !== 'public-component')
    return []

  const runnable = record.stories?.runnable
  const lines: string[] = ['## Playground', '']

  // `hasSeed` is the authority when the caller has it, because
  // `playground-seeds.ts` applies two rules this renderer cannot see (a template
  // that opens no component tag; a tag the library does not export). A page must
  // never promise a playground the site has no seed for, so the two are compared
  // by `validate:docs-pages` as well as wired together here.
  const seeded = hasSeed ?? (runnable?.template !== undefined)
  if (!seeded || runnable === undefined || runnable.template === undefined) {
    // The fallback exists only for callers that pass neither (unit tests of the
    // D1 shape). Generated pages always carry the measured refusal.
    const measured: SeedRefusal = refusal
      ?? (record.stories?.file === undefined
        ? { reason: 'no-stories-file' }
        : { reason: 'no-runnable-story', file: record.stories.file })
    lines.push(
      'No editable playground is published for this component.',
      '',
      refusalSentence(measured),
      '',
    )
    return lines
  }

  const label = runnable.name ?? runnable.id
  lines.push(
    `Editable, running the **${label}** story from \`${record.stories?.file ?? 'the stories file'}\` `
    + `(lines ${runnable.lines[0]}–${runnable.lines[1]}) **verbatim**. `
    + 'Edits run in a sandbox; nothing here is saved.',
    '',
    `<DzPlayground component="${record.name}" />`,
    '',
  )
  return lines
}

export interface ComponentPageInput {
  record: ComponentMetaRecord
  artifact: ComponentMetaArtifact
  /** Hand-written prose from `components/_usage/<Name>.md`, already read. Merged verbatim. */
  usageProse?: string
  /**
   * The generated evidence artifacts (TASK-N2-D2). When present the page gains
   * its *Accessibility and evidence* section; when absent the page is exactly
   * what D1 published, which keeps every D1 unit test meaningful.
   */
  evidence?: EvidenceSources
  /**
   * Public components the seeds artifact actually carries a playground for
   * (TASK-N2-D3). Omitted in unit tests, where the record's own
   * `stories.runnable` is the answer.
   */
  playgroundSeeded?: ReadonlySet<string>
  /**
   * The measured reason each seed-less public component has no playground
   * (TASK-N2-D3), keyed by component name. Omitted in unit tests.
   */
  playgroundRefusals?: ReadonlyMap<string, SeedRefusal>
}

/**
 * One component's page: front matter, the reused `llms-full.txt` section at
 * page level, the contract note, hand-written prose, nested compound parts and
 * the fidelity block.
 */
export function renderComponentPage(input: ComponentPageInput): string {
  const { record, artifact, usageProse, evidence, playgroundSeeded, playgroundRefusals } = input
  const section = renderComponentSection(record, artifact, { level: 1, memberHeadingLevel: 2 })
  const { head, meta, rest } = splitSection(section)
  const parts = compoundPartsOf(record, artifact)

  const provenance = [
    `- **Family:** ${familyLabel(record.family)}`,
    `- **Source:** \`${record.source}\`${record.typesSource === undefined ? '' : ` · types \`${record.typesSource}\``}`,
  ]
  if (parts.length > 0)
    provenance.push(`- **Compound parts:** ${parts.map(p => `\`${p.name}\``).join(', ')}`)

  const body: string[] = [
    ...head,
    ...provenance,
    ...meta,
    '',
    ...HOW_TO_READ,
    '',
    ...rest,
    // TASK-N2-D3. Directly under the static usage snippet, because the two are
    // the same story file read two ways: the snippet is what you paste, the
    // playground is what you press.
    ...renderPlayground(
      record,
      playgroundSeeded === undefined ? undefined : playgroundSeeded.has(record.name),
      playgroundRefusals?.get(record.name),
    ),
  ]

  const prose = stripHtmlComments(usageProse ?? '').trim()
  if (prose !== '') {
    body.push(
      '## Usage notes',
      '',
      '<!-- hand-written prose, merged from components/_usage/'
      + `${record.name}.md — the only non-generated content on this page -->`,
      '',
      prose,
      '',
    )
  }

  if (parts.length > 0) {
    body.push(
      '## Compound parts',
      '',
      `\`${record.name}\` is used with ${parts.length} sub-part${parts.length === 1 ? '' : 's'}, `
      + 'documented here rather than on pages of their own because they are not usable outside it.',
      '',
    )
    for (const part of parts)
      body.push(...renderComponentSection(part, artifact, { level: 3, memberHeadingLevel: 4 }))
  }

  body.push(...renderFidelity(record))

  // D1's §14 seam, taken exactly as offered: one call, after `renderFidelity`,
  // inside `renderComponentPage` — so the freshness gate, the fingerprint, the
  // orphan clause and `validate:docs-pages` all cover the evidence section
  // without a second generator or a second app.
  if (evidence !== undefined)
    body.push(...renderEvidence(record, evidence))

  const description = record.description === ''
    ? `${record.name} — API reference generated from source.`
    : record.description.replace(/\s+/g, ' ').trim()

  const frontMatter = [
    '---',
    `title: ${yamlString(record.name)}`,
    `description: ${yamlString(description)}`,
    'outline: [2, 3]',
    '---',
    '',
    GENERATED_BANNER,
    '',
  ]

  // Deliberately NOT collapsing blank runs: the usage snippet is a verbatim
  // slice of a story file and re-flowing it would stop being verbatim.
  return `${[...frontMatter, ...escapeForVue(body)].join('\n').trimEnd()}\n`
}

// ── The components index ────────────────────────────────────────────────────

/**
 * `components/index.md` — every public component, grouped by family, with its
 * one-line description. This is what makes a family name searchable: the local
 * search index is built from page text, so "overlays" has to appear as text
 * somewhere it can match.
 */
export function renderComponentsIndex(artifact: ComponentMetaArtifact): string {
  const groups = groupByFamily(artifact.components.filter(c => c.kind === 'public-component'))
  const t = artifact.totals
  const lines: string[] = [
    '---',
    'title: "Components"',
    'description: "Every public dzup-ui component, grouped by family, with generated API tables."',
    'outline: [2, 2]',
    '---',
    '',
    GENERATED_BANNER,
    '',
    '# Components',
    '',
    `${t.publicComponents} public components across ${groups.length} families, plus ${t.compoundParts} `
    + 'compound sub-parts documented on their parent\'s page. Every table on every component page is '
    + `extracted from source by \`${artifact.extractor}\`; nothing here is hand-typed.`,
    '',
  ]
  for (const group of groups) {
    lines.push(`## ${group.label}`, '')
    for (const c of group.components) {
      const desc = c.description === '' ? '' : ` — ${c.description.replace(/\s+/g, ' ').trim()}`
      lines.push(`- [${c.name}](./${c.name}.md)${desc}`)
    }
    lines.push('')
  }
  return `${escapeForVue(lines).join('\n').trimEnd()}\n`
}

// ── Navigation data consumed by .vitepress/config.ts ────────────────────────

/** One sidebar group — a family and its public components. */
export interface DocsNavGroup {
  /** Family key, e.g. `overlays`. */
  key: string
  /** Human label, e.g. `Overlays`. */
  text: string
  items: Array<{ text: string, link: string }>
}

/**
 * The data `.vitepress/config.ts` builds its sidebar from, plus the fingerprint
 * the config asserts against the artifact on disk.
 *
 * The fingerprint is a *second* staleness axis and catches a different failure
 * from the freshness gate: the artifact can be regenerated after the pages
 * were, leaving 144 correct-looking pages describing the previous extraction.
 * `vitepress build` then fails on its own, without needing the 20-second
 * re-extraction.
 */
export interface DocsNav {
  generator: string
  /** SHA-256 of the artifact these pages were rendered from. */
  artifactSha256: string
  schemaVersion: string
  extractor: string
  sourceCommit: string
  publicComponents: number
  compoundParts: number
  groups: DocsNavGroup[]
  /**
   * SHA-256 of every evidence artifact the pages were rendered from, by
   * repo-relative path (TASK-N2-D2).
   *
   * The same second staleness axis, widened. D1's fingerprint covered one
   * artifact because one artifact produced every page; the evidence layer reads
   * several, and any of them moving after a render leaves the site publishing a
   * measurement that has since changed. An absent artifact is recorded as
   * absent, so its *appearance* is a change too.
   */
  evidenceSha256: Record<string, string>
  /** The evidence-section counts the site header shows. */
  evidence?: {
    cells: number
    unrunCells: number
    atCells: number
    atExecuted: number
  }
}

/** Build the navigation payload. Pure over the artifact plus the hashes of its inputs. */
export function buildNav(
  artifact: ComponentMetaArtifact,
  artifactSha256: string,
  evidence?: EvidenceSources,
): DocsNav {
  const groups = groupByFamily(artifact.components.filter(c => c.kind === 'public-component'))
  const cells = evidence?.capability.rows.flatMap(r => r.cells) ?? []
  return {
    generator: 'yarn generate:docs-pages (TASK-N2-D1, evidence layer TASK-N2-D2)',
    artifactSha256,
    schemaVersion: artifact.schemaVersion,
    extractor: artifact.extractor,
    sourceCommit: artifact.sourceCommit,
    publicComponents: artifact.totals.publicComponents,
    compoundParts: artifact.totals.compoundParts,
    groups: groups.map(g => ({
      key: g.key,
      text: g.label,
      items: g.components.map(c => ({ text: c.name, link: `/${COMPONENTS_DIR}/${c.name}` })),
    })),
    evidenceSha256: evidence?.fingerprints ?? {},
    ...(evidence === undefined
      ? {}
      : {
          evidence: {
            cells: cells.length,
            unrunCells: cells.filter(c => c.state === 'unrun').length,
            atCells: evidence.atMatrix.entries.reduce((n, e) => n + e.rows.length, 0),
            atExecuted: evidence.atMatrix.entries
              .reduce((n, e) => n + e.rows.filter(r => r.result !== 'unrun').length, 0),
          },
        }),
  }
}
