/**
 * The standalone evidence pages under `/evidence/` (TASK-N2-D2).
 *
 * Six generated pages: the hub, the capability matrix, the assistive-technology
 * matrix, the accessibility conformance statement, the browser-support
 * statement, and the styling-posture statement.
 *
 * ## Generated pages, including the two "statements"
 *
 * The task calls the styling and browser statements *authored prose (they are
 * policy, not data)* — and requires that *every factual claim in them (engine
 * versions, layer names, pilot counts) is generated or omitted*. Those two
 * requirements pull in opposite directions if the page is a hand-written
 * markdown file, because nothing then stops a number being typed into it.
 *
 * So the prose lives in `statements.ts` (hand-written, gated to contain no
 * metric at all) and the *page* is generated around it. That puts both
 * statements inside `validate:docs-pages`: hand-editing one fails the gate, and
 * a number can only reach the page by being read out of an artifact here.
 *
 * ## Everything under `apps/docs/evidence/` is generated
 *
 * `apps/docs/guide/` is hand-written, `apps/docs/components/` and
 * `apps/docs/evidence/` are generated, and the orphan clause enforces the
 * boundary in both generated directories.
 *
 * @module @dzup-ui/tooling/docs/evidence-pages
 */

import type { ComponentMetaArtifact } from '../meta/component-meta.ts'
import type { EvidenceSources, WcagSurface } from './evidence.ts'
import type { StatementProse } from './statements.ts'
import { escapeForVue, yamlString } from './docs-pages.ts'
import {
  apgLink,
  cell,
  shortCommit,
  wcagUnderstandingUrl,
} from './evidence.ts'
import {
  ACCESSIBILITY_STATEMENT,
  BROWSER_SUPPORT,
  EVIDENCE_INDEX,
  STYLING_POSTURE,
} from './statements.ts'

/** Directory (relative to the docs app root) the generated evidence pages live in. */
export const EVIDENCE_DIR = 'evidence'

/**
 * The banner every evidence page carries.
 *
 * Deliberately not `GENERATED_BANNER`: that one names `component-meta.json` and
 * points an editor at `components/_usage/`, neither of which is true here. A
 * banner that misdescribes where its own content comes from is a small lie in
 * the one place on the page whose whole job is provenance.
 */
export const EVIDENCE_BANNER
  = '<!-- GENERATED by `yarn generate:docs-pages` from the evidence artifacts listed under\n'
    + '     Provenance at the foot of this page. The prose is authored in\n'
    + '     packages/tooling/src/docs/statements.ts and contains no metric; every number here is\n'
    + '     read from an artifact at build time. Edits to this file are overwritten. -->'

/** Front matter + banner, shared by every page in this module. */
function pageHead(statement: Pick<StatementProse, 'title' | 'description'>, outline: string): string[] {
  return [
    '---',
    `title: ${yamlString(statement.title)}`,
    `description: ${yamlString(statement.description)}`,
    `outline: ${outline}`,
    '---',
    '',
    EVIDENCE_BANNER,
    '',
  ]
}

/** The provenance footer every evidence page carries. Composed, never typed. */
function provenance(ev: EvidenceSources, paths: readonly string[]): string[] {
  return [
    '## Provenance',
    '',
    'Every number on this page is read from a generated artifact at build time. The artifacts, and the',
    'SHA-256 of the exact bytes these pages were rendered from:',
    '',
    '| Artifact | sha256 | Present |',
    '| --- | --- | --- |',
    ...paths.map((p) => {
      const fp = ev.fingerprints[p]
      return `| \`${p}\` | ${fp === undefined ? '—' : `\`${fp.slice(0, 16)}…\``} | ${fp === undefined ? '**absent in this checkout**' : 'yes'} |`
    }),
    '',
    `Capability matrix \`sourceCommit\` \`${shortCommit(ev.capability.sourceCommit)}\` · quality matrix `
    + `\`${shortCommit(ev.quality.sourceCommit)}\`.`,
    '',
    '::: warning Standing',
    'Locally qualified. Not continuous-integration evidence, not release evidence, not production',
    'evidence. See [what this evidence is admissible for](/evidence/#what-this-evidence-is-admissible-for).',
    ':::',
    '',
  ]
}

// ---------------------------------------------------------------------------
// /evidence/ — the hub
// ---------------------------------------------------------------------------

/** Catalogue-wide cell arithmetic, computed rather than quoted. */
export interface EvidenceTotals {
  components: number
  cells: number
  byState: Record<string, number>
  byKind: Map<string, { origin: string, states: Record<string, number>, unrun: string[], stale: string[] }>
  atComponents: number
  atPairs: number
  atCells: number
  atExecuted: number
}

/** Compute the catalogue totals from the matrices. Pure. */
export function computeTotals(ev: EvidenceSources): EvidenceTotals {
  const byState: Record<string, number> = {}
  const byKind: EvidenceTotals['byKind'] = new Map()
  let cells = 0
  for (const row of ev.capability.rows) {
    for (const c of row.cells) {
      cells += 1
      byState[c.state] = (byState[c.state] ?? 0) + 1
      const entry = byKind.get(c.kind) ?? { origin: c.origin, states: {}, unrun: [], stale: [] }
      entry.states[c.state] = (entry.states[c.state] ?? 0) + 1
      if (c.state === 'unrun')
        entry.unrun.push(row.component)
      if (c.state === 'stale')
        entry.stale.push(row.component)
      byKind.set(c.kind, entry)
    }
  }
  const atCells = ev.atMatrix.entries.reduce((n, e) => n + e.rows.length, 0)
  const atExecuted = ev.atMatrix.entries
    .reduce((n, e) => n + e.rows.filter(r => r.result !== 'unrun').length, 0)
  return {
    components: ev.capability.rows.length,
    cells,
    byState,
    byKind,
    atComponents: ev.atMatrix.entries.length,
    atPairs: ev.atMatrix.pairs.length,
    atCells,
    atExecuted,
  }
}

/** `/evidence/` — the hub. */
export function renderEvidenceIndex(ev: EvidenceSources): string {
  const t = computeTotals(ev)
  const order = ['pass', 'present', 'stale', 'excepted', 'unrun']
  const kinds = [...t.byKind.keys()]
  const lines: string[] = [
    ...pageHead(EVIDENCE_INDEX, '[2, 3]'),
    `# ${EVIDENCE_INDEX.title}`,
    '',
    ...EVIDENCE_INDEX.blocks.position!,
    '',
    '## The catalogue, in one table',
    '',
    `**${t.cells} evidence cells** across **${t.components} public components** and `
    + `**${kinds.length} kinds of evidence**.`,
    '',
    '| State | Cells |',
    '| --- | --- |',
    ...order
      .filter(s => t.byState[s] !== undefined)
      .map(s => `| ${s === 'unrun' ? '**`unrun`**' : `\`${s}\``} | ${t.byState[s]} |`),
    ...Object.keys(t.byState).filter(s => !order.includes(s)).map(s => `| \`${s}\` | ${t.byState[s]} |`),
    '',
    `Of those, **${t.byState.unrun ?? 0} are \`unrun\`** — nothing has measured them — and `
    + `**${t.byState.stale ?? 0} are \`stale\`**. Which cells, on which components, is on `
    + '[the capability matrix](/evidence/capability-matrix) and on each component page.',
    '',
    `The assistive-technology matrix is counted separately, and its number is **${t.atExecuted} of `
    + `${t.atCells}**: ${t.atComponents} components times ${t.atPairs} declared AT/browser pairings, `
    + `of which ${t.atExecuted} have been executed. See [the AT matrix](/evidence/at-matrix).`,
    '',
    ...EVIDENCE_INDEX.blocks.howToRead!,
    '',
    ...EVIDENCE_INDEX.blocks.admissibility!,
    '',
    '## The pages',
    '',
    '| Page | What it holds |',
    '| --- | --- |',
    '| [Capability matrix](/evidence/capability-matrix) | Every evidence cell for every public component, by kind and by component. |',
    '| [Assistive technology](/evidence/at-matrix) | Every AT/browser pairing every component owes, and what has been run. |',
    '| [Accessibility conformance](/evidence/accessibility) | The WCAG position, including the open gap. |',
    '| [Browser support](/evidence/browser-support) | The engine lane, and what it does not cover. |',
    '| [Styling posture](/evidence/styling-posture) | Restyleable by contract, not unstyled. |',
    '',
    ...provenance(ev, [
      'packages/core/docs/capability-matrix.json',
      'packages/core/docs/quality-matrix.json',
      'e2e/at-matrix/index.json',
    ]),
  ]
  return `${escapeForVue(lines).join('\n').trimEnd()}\n`
}

// ---------------------------------------------------------------------------
// /evidence/capability-matrix
// ---------------------------------------------------------------------------

/** `/evidence/capability-matrix` — the whole matrix, browsable. */
export function renderCapabilityMatrixPage(ev: EvidenceSources): string {
  const t = computeTotals(ev)
  const order = ['pass', 'present', 'stale', 'excepted', 'unrun']
  const tiers = Object.keys(ev.capability.totals).sort()

  const lines: string[] = [
    ...pageHead({
      title: 'Capability matrix',
      description:
        'Every evidence cell for every public dzup-ui component, by kind and by component, with unrun and stale cells named.',
    }, '[2, 2]'),
    '# Capability matrix',
    '',
    `What each public component owes, and what has been measured. **${t.cells} cells** over `
    + `**${t.components} components**, generated from the quality tiers, the component traits and the `
    + 'declared security boundaries — never assigned by hand.',
    '',
    '::: info Cells are named, not counted',
    'Where a kind is `unrun` or `stale` this page lists **which components**. A count on its own tells',
    'a reader that something is missing without telling them what, which is the shape of evidence that',
    'stops being read.',
    ':::',
    '',
    '## Where the measurements come from',
    '',
    'The matrix is a join, and a missing input silently turns cells into `unrun` rather than failing.',
    'So the inputs are published with it.',
    '',
    '| Input | Path | Available |',
    '| --- | --- | --- |',
    ...Object.entries(ev.capability.inputs).map(
      ([key, v]) => `| \`${key}\` | \`${v.path}\` | ${v.available ? 'yes' : '**no**'} |`,
    ),
    '',
  ]

  const noted = Object.entries(ev.capability.inputs).filter(([, v]) => v.note !== undefined)
  if (noted.length > 0) {
    lines.push('The inputs that carry a recorded caveat:', '')
    for (const [key, v] of noted)
      lines.push(`- **\`${key}\`** — ${cell(v.note)}`)
    lines.push('')
  }

  lines.push(
    '## By risk tier',
    '',
    `| Tier | ${order.join(' | ')} |`,
    `| --- | ${order.map(() => '---').join(' | ')} |`,
    ...tiers.map((tier) => {
      const row = ev.capability.totals[tier] ?? {}
      return `| \`${tier}\` | ${order.map(s => row[s] ?? 0).join(' | ')} |`
    }),
    '',
    '## By kind of evidence',
    '',
    'Each kind, what puts it on a component, and how the cells resolved.',
    '',
    `| Evidence | Required by | Rows | ${order.join(' | ')} |`,
    `| --- | --- | --- | ${order.map(() => '---').join(' | ')} |`,
  )
  for (const [kind, entry] of t.byKind) {
    const rows = Object.values(entry.states).reduce((a, b) => a + b, 0)
    lines.push(
      `| \`${kind}\` | ${cell(entry.origin)} | ${rows} | `
      + `${order.map(s => entry.states[s] ?? 0).join(' | ')} |`,
    )
  }
  lines.push('')

  const withGaps = [...t.byKind.entries()].filter(([, e]) => e.unrun.length > 0 || e.stale.length > 0)
  lines.push(
    `## The ${withGaps.length} kinds with an unmeasured or stale cell, named`,
    '',
  )
  for (const [kind, entry] of withGaps) {
    lines.push(`::: details \`${kind}\` — ${entry.unrun.length} unrun, ${entry.stale.length} stale`)
    if (entry.unrun.length > 0)
      lines.push(`**unrun (${entry.unrun.length}):** ${entry.unrun.map(c => `\`${c}\``).join(', ')}`, '')
    if (entry.stale.length > 0)
      lines.push(`**stale (${entry.stale.length}):** ${entry.stale.map(c => `\`${c}\``).join(', ')}`, '')
    lines.push(':::', '')
  }

  lines.push(
    '## Every component',
    '',
    `All ${t.components} rows. Follow a component to see its cells with their artifacts and notes.`,
    '',
    '| Component | Family | Tier | APG pattern | Boundary | Cells | Unrun | Stale |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
  )
  for (const row of [...ev.capability.rows].sort((a, b) => a.component.localeCompare(b.component, 'en'))) {
    const unrun = row.cells.filter(c => c.state === 'unrun').map(c => c.kind)
    const stale = row.cells.filter(c => c.state === 'stale').map(c => c.kind)
    const link = apgLink(row.pattern)
    lines.push(
      `| [${row.component}](/components/${row.component}#accessibility-and-evidence) `
      + `| ${cell(row.family)} | \`${row.tier}\` `
      + `| ${link === undefined ? `\`${row.pattern}\`` : `[\`${row.pattern}\`](${link})`} `
      + `| \`${row.securityBoundary}\` | ${row.cells.length} `
      + `| ${unrun.length === 0 ? '—' : `**${unrun.map(k => `\`${k}\``).join(', ')}**`} `
      + `| ${stale.length === 0 ? '—' : stale.map(k => `\`${k}\``).join(', ')} |`,
    )
  }
  lines.push('')

  lines.push(...provenance(ev, [
    'packages/core/docs/capability-matrix.json',
    'packages/core/docs/quality-matrix.json',
  ]))
  return `${escapeForVue(lines).join('\n').trimEnd()}\n`
}

// ---------------------------------------------------------------------------
// /evidence/at-matrix
// ---------------------------------------------------------------------------

/** `/evidence/at-matrix` — every declared AT/browser pairing, and what has run. */
export function renderAtMatrixPage(ev: EvidenceSources): string {
  const t = computeTotals(ev)
  const byTier = new Map<string, number>()
  for (const e of ev.atMatrix.entries)
    byTier.set(e.tier, (byTier.get(e.tier) ?? 0) + 1)

  const lines: string[] = [
    ...pageHead({
      title: 'Assistive-technology matrix',
      description:
        'Every screen-reader and browser pairing each dzup-ui component owes, and the honest count of how many have been executed.',
    }, '[2, 2]'),
    '# Assistive-technology matrix',
    '',
    `**${t.atExecuted} of ${t.atCells} cells executed.**`,
    '',
    t.atExecuted === 0
      ? 'That is the whole result. No component in this library has been driven with a screen reader '
      + 'and had the result recorded. Everything below describes what is owed, not what is known.'
      : 'The unexecuted cells below are listed with the same weight as the executed ones.',
    '',
    ...ACCESSIBILITY_STATEMENT.blocks.at!,
    '',
    ...ACCESSIBILITY_STATEMENT.blocks.cellDefect!,
    '',
    '## The declared pairings',
    '',
    `A cell is one component times one pairing. ${ev.atMatrix.pairs.length} pairings are declared, and `
    + 'each is here because it can expose something the others cannot.',
    '',
    '| Pairing | Assistive technology | Browser | Platform | What only it exposes |',
    '| --- | --- | --- | --- | --- |',
    ...ev.atMatrix.pairs.map(
      p => `| \`${p.id}\` | ${cell(p.at)} | ${cell(p.browser)} | ${cell(p.platform)} | ${cell(p.purpose)} |`,
    ),
    '',
    '## Which components owe a run',
    '',
    `${t.atComponents} components carry a row: `
    + `${[...byTier.entries()].sort().map(([tier, n]) => `${n} at Tier ${tier}`).join(', ')}. `
    + 'The lowest risk tier is excluded from the matrix entirely.',
    '',
    '::: warning The matrix declares no tier-differentiated obligation',
    'Every component in it owes every pairing, whatever its tier — the obligation is inherited from the',
    'lowest tier that carries it and is never widened. Whether the highest-risk components should owe',
    'more than the lowest is an open owner decision, recorded rather than quietly answered.',
    ':::',
    '',
    '| Component | Tier | APG pattern | Tasks per pairing | Executed | Executable script |',
    '| --- | --- | --- | --- | --- | --- |',
  ]
  for (const e of [...ev.atMatrix.entries].sort((a, b) => a.component.localeCompare(b.component, 'en'))) {
    const executed = e.rows.filter(r => r.result !== 'unrun').length
    const script = ev.atScripts[e.component]
    lines.push(
      `| [${e.component}](/components/${e.component}#assistive-technology) | \`${e.tier}\` `
      + `| \`${e.pattern}\` | ${e.tasks.length} | `
      + `${executed === 0 ? `**0 of ${e.rows.length}**` : `${executed} of ${e.rows.length}`} `
      + `| ${script === undefined ? '—' : `\`${script}\``} |`,
    )
  }
  const scripted = ev.atMatrix.entries.filter(e => ev.atScripts[e.component] !== undefined)
  lines.push(
    '',
    `**${scripted.length} of ${ev.atMatrix.entries.length} components have an executable script.** A `
    + 'script names the story to open, the keys to press and the announcement each step must produce; '
    + 'its expectations are derived from the pattern rather than from what the component currently '
    + 'does, so that a real defect is recorded as a failure instead of being written into the '
    + 'expectation. The remainder owe cells with no script yet.',
    '',
    '## What a recorded run will look like',
    '',
    'The record is append-only: a generator can rewrite the header but never a result row, and a row',
    'that says anything other than `unrun` must carry the tester, the date, the assistive-technology',
    'and browser versions, and the commit the component was at. A result with nothing behind it is',
    'worse than `unrun`, because `unrun` is true.',
    '',
    ...provenance(ev, ['e2e/at-matrix/index.json', 'packages/core/docs/capability-matrix.json']),
  )
  return `${escapeForVue(lines).join('\n').trimEnd()}\n`
}

// ---------------------------------------------------------------------------
// /evidence/accessibility
// ---------------------------------------------------------------------------

/** One row of the SC 2.5.7 audit, rendered for the conformance page. */
function auditRow(s: WcagSurface): string {
  return `| [${s.component}](/components/${s.component}#accessibility-and-evidence) `
    + `| ${cell(s.operation)} | ${cell(s.keyboardAlternative)} `
    + `| ${s.singlePointerNoDrag === null ? '**none**' : cell(s.singlePointerNoDrag)} `
    + `| ${s.state === 'gap' ? '**gap**' : 'met'} |`
}

/** `/evidence/accessibility` — the conformance statement. */
export function renderAccessibilityPage(ev: EvidenceSources): string {
  const t = computeTotals(ev)
  const dev = ev.wcagDeviations
  const gaps = dev.surfaces.filter(s => s.state === 'gap')
  const met = dev.surfaces.filter(s => s.state === 'met')
  const scCount = new Map<string, number>()
  for (const c of ev.quality.components) {
    for (const id of c.wcag) scCount.set(id, (scCount.get(id) ?? 0) + 1)
  }

  const kbd = t.byKind.get('keyboard-spec')
  const axe = t.byKind.get('axe')
  const patternless = ev.quality.components.filter(c => apgLink(c.pattern) === undefined)

  const lines: string[] = [
    ...pageHead(ACCESSIBILITY_STATEMENT, '[2, 3]'),
    `# ${ACCESSIBILITY_STATEMENT.title}`,
    '',
    ...ACCESSIBILITY_STATEMENT.blocks.position!,
    '',
    ...ACCESSIBILITY_STATEMENT.blocks.open!,
    '',
    `::: danger SC ${dev.criterion.id} ${dev.criterion.name} (level ${dev.criterion.level}, new in `
    + `WCAG ${dev.criterion.since}) is not met on ${gaps.length} of ${dev.surfaces.length} drag surfaces`,
    `**${cell(dev.conformanceStatement)}**`,
    '',
    `> ${cell(dev.criterion.text)}`,
    '',
    `The gap is on ${gaps.map(s => `\`${s.component}\``).join(', ')}; the audit below names each`,
    'operation. Every one of them is keyboard-operable, and a keyboard path satisfies SC 2.1.1, not',
    'this one: the criterion is about pointer input and requires a single pointer without dragging.',
    '',
    `[Understanding SC ${dev.criterion.id}](${dev.criterion.url})`,
    ':::',
    '',
    '### The audit',
    '',
    `Scope is not a judgement call: every component carrying the \`drags\` trait was audited, and the `
    + `trait names ${dev.surfaces.length}.`,
    '',
    `| Component | Drag operation | Keyboard (SC 2.1.1) | Single pointer, no drag (SC ${dev.criterion.id}) | State |`,
    '| --- | --- | --- | --- | --- |',
    ...gaps.map(auditRow),
    ...met.map(auditRow),
    '',
  ]

  for (const s of met.filter(s => s.caveat !== undefined)) {
    lines.push(
      `::: warning ${s.component} — a configuration caveat`,
      cell(s.caveat),
      ':::',
      '',
    )
  }

  lines.push(
    '### Why it is not fixed here',
    '',
    ...gaps.map(s => `- **${s.component}** — ${cell(s.ownerDecision)}`),
    '',
    `None of them qualifies for the criterion's own exceptions.`,
    '',
    ...[...new Set(gaps.map(s => cell(s.notEssential)))].map(reason => `- ${reason}`),
    '',
    '**The scoped follow-up, as handed to the owner:**',
    '',
    `> ${cell(dev.followUp)}`,
    '',
    `Measured by \`${cell(dev.recordedAt.measuredBy)}\`, recorded in `
    + `\`packages/core/docs/wcag-deviations.json\` at \`${shortCommit(dev.recordedAt.sourceCommit ?? '')}\` `
    + `(${cell(dev.recordedAt.admissibility)}).`,
    '',
    ...ACCESSIBILITY_STATEMENT.blocks.at!,
    '',
    `Measured: **${t.atExecuted} of ${t.atCells} cells**, over ${t.atComponents} components and `
    + `${t.atPairs} pairings. [The AT matrix](/evidence/at-matrix) lists every one.`,
    '',
    ...ACCESSIBILITY_STATEMENT.blocks.cellDefect!,
    '',
    ...ACCESSIBILITY_STATEMENT.blocks.keyboard!,
    '',
    kbd === undefined
      ? '_No `keyboard-spec` cell exists in the matrix._'
      : `Measured today: of the ${Object.values(kbd.states).reduce((a, b) => a + b, 0)} components that `
        + `owe a \`keyboard-spec\`, ${kbd.states.present ?? 0} have a specification asserting at least one `
        + `key sequence, ${kbd.states.unrun ?? 0} do not, and ${kbd.states.excepted ?? 0} are excepted. `
        + 'None of that is a table of bindings, and the repository has nowhere to hold one.',
    '',
    ...ACCESSIBILITY_STATEMENT.blocks.scope!,
    '',
    '### The criteria, and how many components each applies to',
    '',
    `The published dictionary carries ${ev.quality.wcag.length} success criteria — the ones a component `
    + 'library can actually fail. A criterion applying to no component means nothing in the catalogue '
    + 'declares the behaviour it governs.',
    '',
    '| SC | Criterion | Level | New in | Components in scope |',
    '| --- | --- | --- | --- | --- |',
    ...ev.quality.wcag.map(
      c => `| [${c.id}](${wcagUnderstandingUrl(c.name)}) | ${cell(c.name)} | ${c.level} | WCAG ${c.since} `
        + `| ${scCount.get(c.id) ?? 0} of ${ev.quality.components.length} |`,
    ),
    '',
    '### The automated lane',
    '',
    axe === undefined
      ? '_No automated accessibility cell exists in the matrix._'
      : `An automated accessibility assertion is bound to ${axe.states.present ?? 0} of `
        + `${Object.values(axe.states).reduce((a, b) => a + b, 0)} components; `
        + `${axe.states.unrun ?? 0} have none. Automated checking finds a minority of accessibility `
        + 'defects even where it passes, so this is published as coverage, never as conformance.',
    '',
    '### Components with no APG pattern',
    '',
    patternless.length === 0
      ? 'Every component maps to a WAI-ARIA Authoring Practices pattern.'
      : `${patternless.length} of ${ev.quality.components.length} components map to no APG pattern — `
        + `they are declared \`custom\` or \`none\`, and a declaration of \`custom\` is required to carry `
        + 'a written reason, which their pages print. There is no keyboard contract to link for them, '
        + 'and their pages say so rather than linking a pattern that does not describe them.',
    '',
    ...provenance(ev, [
      'packages/core/docs/quality-matrix.json',
      'packages/core/docs/capability-matrix.json',
      'packages/core/docs/wcag-deviations.json',
      'e2e/at-matrix/index.json',
    ]),
  )
  return `${escapeForVue(lines).join('\n').trimEnd()}\n`
}

// ---------------------------------------------------------------------------
// /evidence/browser-support
// ---------------------------------------------------------------------------

/** `/evidence/browser-support` — the statement, wrapped around the engine lane. */
export function renderBrowserSupportPage(ev: EvidenceSources): string {
  const engines = ev.engines
  const lines: string[] = [
    ...pageHead(BROWSER_SUPPORT, '[2, 3]'),
    `# ${BROWSER_SUPPORT.title}`,
    '',
    ...BROWSER_SUPPORT.blocks.position!,
    '',
    ...BROWSER_SUPPORT.blocks.whatRuns!,
    '',
  ]

  if (engines === undefined) {
    lines.push(
      '::: danger No engine-lane record exists in this checkout',
      '`e2e/matrix/engine-ratchets.json` is absent, so **no engine numbers are shown on this page**.',
      'Nothing here should be read as browser evidence. The lane exists and can be run; its record is',
      'not present, and rendering the page around the absence is the only honest option — a browser',
      'lane whose record has gone missing is exactly how an evidence surface starts overstating itself.',
      ':::',
      '',
    )
  }
  else {
    const names = Object.keys(engines.engines)
    const conditions = [...new Set(names.flatMap(n => engines.engines[n]!.conditionsRun))]
    lines.push(
      `| Engine | Version | Conditions | Targets | Cells run | Passed | Unexpected failures | Wall clock | Run on |`,
      `| --- | --- | --- | --- | --- | --- | --- | --- | --- |`,
      ...names.map((name) => {
        const e = engines.engines[name]!
        return `| \`${name}\` | ${cell(e.version)} | ${e.conditionsRun.length} `
          + `| ${e.summary.runnableTargets} | ${e.summary.cellsRun} | ${e.summary.passed} `
          + `| ${e.summary.unexpectedFailure} | ${cell(e.summary.wallClock)} | ${cell(e.summary.ranAt)} |`
      }),
      '',
      `Conditions: ${conditions.map(c => `\`${c}\``).join(', ')}. `
      + `Driver: Playwright \`${cell(engines.playwrightVersion)}\` on \`${cell(engines.platform)}\`.`,
      '',
      `**Cross-engine result, measured \`${cell(engines.crossEngineResult.measuredAt)}\`:** `
      + `${cell(engines.crossEngineResult.note)}`,
      '',
      `The cross-engine ledger of expected failures holds `
      + `**${engines.crossEngineResult.ledgerEntries} entries**`
      + `${ev.knownFailures === undefined ? '' : ` (\`e2e/matrix/known-failures.json\`, closed by \`${cell(ev.knownFailures.closedBy?.split('.')[0])}\`)`}. `
      + 'A listed cell still runs and still costs wall-clock; the lane fails if one unexpectedly passes, '
      + 'so the file can only shrink.',
      '',
      `**How far this goes:** ${cell(engines.admissibility)}`,
      '',
      `**Method:** ${cell(engines.method)}`,
      '',
    )
    const declaredUnrun = names
      .map(n => engines.engines[n]!.summary.declaredUnrunTargets)
      .reduce((a, b) => Math.max(a, b), 0)
    if (declaredUnrun > 0) {
      lines.push(
        `::: warning ${declaredUnrun} target${declaredUnrun === 1 ? '' : 's'} in the lane `
        + `${declaredUnrun === 1 ? 'is' : 'are'} declared unrun`,
        'A component with no published story cannot be driven by a story-based lane. It is declared',
        'unrun rather than skipped, so it stays visible in the arithmetic instead of disappearing from',
        'the denominator.',
        ':::',
        '',
      )
    }
  }

  lines.push(
    ...BROWSER_SUPPORT.blocks.webkit!,
    '',
    ...BROWSER_SUPPORT.blocks.history!,
    '',
    ...BROWSER_SUPPORT.blocks.baseline!,
    '',
    ...BROWSER_SUPPORT.blocks.notMeasured!,
    '',
    ...provenance(ev, [
      'e2e/matrix/engine-ratchets.json',
      'e2e/matrix/known-failures.json',
      'packages/core/docs/capability-matrix.json',
    ]),
  )
  return `${escapeForVue(lines).join('\n').trimEnd()}\n`
}

// ---------------------------------------------------------------------------
// /evidence/styling-posture
// ---------------------------------------------------------------------------

/** `/evidence/styling-posture` — the statement, with its counts generated. */
export function renderStylingPosturePage(
  ev: EvidenceSources,
  artifact: ComponentMetaArtifact,
): string {
  const declaring = ev.capability.rows.filter(r => r.anatomy === 'declared').map(r => r.component)
  const uiPublic = artifact.components
    .filter(c => c.kind === 'public-component' && c.props.some(p => p.name === 'ui'))
    .map(c => c.name)
  const uiParts = artifact.components
    .filter(c => c.kind === 'compound-part' && c.props.some(p => p.name === 'ui'))
    .map(c => c.name)
  const total = ev.capability.rows.length

  const lines: string[] = [
    ...pageHead(STYLING_POSTURE, '[2, 3]'),
    `# ${STYLING_POSTURE.title}`,
    '',
    ...STYLING_POSTURE.blocks.position!,
    '',
    ...STYLING_POSTURE.blocks.whyCorrected!,
    '',
    ...STYLING_POSTURE.blocks.contract!,
    '',
    '| Layer | What it is | What is measured today |',
    '| --- | --- | --- |',
    '| Design tokens | `--dz-*` custom properties generated from the TypeScript token maps in `@dzup-ui/tokens`. The interchange surface. | Exported as a Design Tokens Community Group document and round-trip verified against the emitted stylesheet in both cascades. |',
    '| Component tokens | `--dz-{component}-{property}`, resolving to the global tokens. Re-map one and every instance follows. | Every CSS value in the library goes through `var(--dz-*)`; raw colour literals fail the token validator. |',
    '| Typed recipes | Styling written with `tv()` in a `.variants.ts` file beside each component. | No `<style scoped>` and no hard-coded colour anywhere in the library. |',
    `| Stable \`data-part\` / \`data-state\` | Selectable from your own stylesheet, on components that have declared an anatomy. | **${declaring.length} of ${total}** components have declared one: ${declaring.map(c => `\`${c}\``).join(', ')}. |`,
    `| The typed \`ui\` prop | A per-instance override keyed by part name, so one instance can be restyled without a selector war. | **${uiPublic.length} of ${total}** public components declare it: ${uiPublic.map(c => `\`${c}\``).join(', ')}${uiParts.length === 0 ? '' : `, plus the compound part${uiParts.length === 1 ? '' : 's'} ${uiParts.map(c => `\`${c}\``).join(', ')}`}. |`,
    '',
    '::: warning The last two rows are a rollout, and the numbers say so',
    `A component that has not declared an anatomy has **not declared** its parts. That is not the same`,
    `claim as having none, and this site never collapses the two: ${total - declaring.length} component `
    + 'pages print nothing under parts because nothing generated says what their parts are, not because',
    'they have none.',
    ':::',
    '',
    ...STYLING_POSTURE.blocks.cascade!,
    '',
    ev.cascadeLayers.length === 0
      ? '_The layer statement could not be read from the library stylesheet, so the layer names are not shown._'
      : `The layers, in the order the library declares them: `
        + `${ev.cascadeLayers.map(l => `\`${l}\``).join(', ')}. Read from the single \`@layer\` statement in `
        + '`packages/core/src/styles/base.css`; nothing on this page names a layer that stylesheet does not.',
    '',
    ...STYLING_POSTURE.blocks.notClaimed!,
    '',
    '## Where to go next',
    '',
    '- [The styling contract](/guide/styling-contract) — how to actually restyle a component.',
    '- [Design tokens](/guide/tokens) — the token tiers and how to re-map them.',
    '- A component page prints an **Anatomy parts (ADR-19)** line when the component has declared one,',
    '  and prints nothing when it has not.',
    '',
    ...provenance(ev, [
      'packages/core/docs/capability-matrix.json',
      'packages/core/src/styles/base.css',
    ]),
  ]
  return `${escapeForVue(lines).join('\n').trimEnd()}\n`
}
