/**
 * `yarn generate:llms` — assemble `llms.txt` and `llms-full.txt` from the
 * component-metadata artifact plus the curated intro source (TASK-N2-A3).
 *
 * WHERE THE OUTPUT LIVES, AND WHY IT IS COMMITTED
 *
 * `packages/core/docs/llms.txt` and `packages/core/docs/llms-full.txt`, beside
 * `component-meta.json` and `capability-matrix.json` — the generated-truth home
 * in this repository.
 *
 * The files these replace were **git-ignored build outputs**
 * (`apps/storybook/public/llms*.txt`, `apps/storybook/.gitignore:14`). Nothing
 * in the repository recorded what dzup-ui was telling coding agents about
 * itself: you had to run a Storybook build to find out, and a review could not
 * see a change to it. A freshness gate of the "committed output vs regenerated
 * output" kind — the one `validate:readme-facts` applies to README versions —
 * needs a committed output to compare against, so there now is one.
 *
 * `packages/core`'s npm `files` is `["LICENSE","README.md","dist"]`, so this
 * directory does not ship to npm. Committing it costs a diff, not a download.
 *
 * HOW THE APPS SERVE IT
 *
 * `apps/storybook`'s `build:llms` copies these two files into
 * `apps/storybook/public/`, which Storybook copies into `storybook-static/`,
 * which the landing build nests at `/storybook/`. So both shipping apps serve
 * the same generated bytes and neither has a copy of the logic. The landing
 * site's own `/llms.txt` is a **different document** — the blocks catalog —
 * generated by `apps/landing/scripts/build-registry.ts`; see the handoff §2.
 *
 * `--check` exits non-zero when the committed files disagree with a fresh
 * render, printing the first differing line. `validate:llms` calls it.
 *
 * @module @dzup-ui/tooling/llms/generate-llms
 */

import type { ComponentMetaArtifact } from '../meta/component-meta.ts'
import { Buffer } from 'node:buffer'
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { ROOT } from '../ownership/generate-ownership-manifest.ts'
import { renderFull, renderIndex } from './render-llms.ts'

/** The metadata artifact these files are assembled from (TASK-N2-A2, constraint B9). */
export const COMPONENT_META_PATH = join(ROOT, 'packages/core/docs/component-meta.json')

/** Canonical, committed output — the concise index. */
export const LLMS_INDEX_PATH = join(ROOT, 'packages/core/docs/llms.txt')
/** Canonical, committed output — the full per-component API. */
export const LLMS_FULL_PATH = join(ROOT, 'packages/core/docs/llms-full.txt')

/** Repo-relative, forward-slashed — the form every message prints. */
export function rel(abs: string): string {
  return abs.replace(/\\/g, '/').replace(`${ROOT.replace(/\\/g, '/')}/`, '')
}

/** Read the artifact, or fail with the command that produces it. */
export function readComponentMeta(path: string = COMPONENT_META_PATH): ComponentMetaArtifact {
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as ComponentMetaArtifact
  }
  catch {
    throw new Error(
      `${rel(path)} is missing or unreadable. Run \`yarn generate:component-meta\` first — `
      + `llms.txt is a projection of it, not an independent extraction (constraint B9).`,
    )
  }
}

/** Both rendered documents, keyed by their output path. */
export function renderLlms(artifact: ComponentMetaArtifact): Array<[string, string]> {
  return [
    [LLMS_INDEX_PATH, renderIndex(artifact)],
    [LLMS_FULL_PATH, renderFull(artifact)],
  ]
}

/**
 * First 1-based line at which two documents differ, or `-1` when identical.
 * Reported instead of a full diff because these files are up to ~10k lines.
 */
export function firstDifferingLine(a: string, b: string): number {
  const al = a.split('\n')
  const bl = b.split('\n')
  const n = Math.max(al.length, bl.length)
  for (let i = 0; i < n; i++) {
    if (al[i] !== bl[i])
      return i + 1
  }
  return -1
}

/** Stale-file messages, one per output that disagrees with a fresh render. */
export function checkLlms(artifact: ComponentMetaArtifact): string[] {
  const problems: string[] = []
  for (const [path, fresh] of renderLlms(artifact)) {
    let onDisk: string
    try {
      onDisk = readFileSync(path, 'utf8')
    }
    catch {
      problems.push(`${rel(path)} does not exist. Run \`yarn generate:llms\`.`)
      continue
    }
    if (onDisk !== fresh) {
      problems.push(
        `${rel(path)} is STALE — it disagrees with a fresh render of `
        + `${rel(COMPONENT_META_PATH)} plus the curated intro source `
        + `(committed ${onDisk.length} chars, fresh ${fresh.length} chars; first difference at `
        + `line ${firstDifferingLine(onDisk, fresh)}). Run \`yarn generate:llms\`.`,
      )
    }
  }
  return problems
}

/* c8 ignore start -- CLI entry point, exercised via `tsx`, not the unit tests. */
const isMain = process.argv[1] !== undefined
  && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))

if (isMain) {
  const artifact = readComponentMeta()
  if (process.argv.includes('--check')) {
    const problems = checkLlms(artifact)
    for (const p of problems)
      console.error(`  ✗ ${p}`)
    if (problems.length > 0)
      process.exitCode = 1
    else console.warn(`  ✓ llms docs fresh — ${rel(LLMS_INDEX_PATH)}, ${rel(LLMS_FULL_PATH)}`)
  }
  else {
    for (const [path, text] of renderLlms(artifact))
      writeFileSync(path, text, 'utf8')
    const index = renderIndex(artifact)
    const full = renderFull(artifact)
    console.warn(
      `▸ llms: ${artifact.totals.components} components `
      + `(${artifact.totals.publicComponents} public, ${artifact.totals.compoundParts} compound parts) `
      + `from ${artifact.extractor}\n`
      + `  → ${rel(LLMS_INDEX_PATH)} (${Buffer.byteLength(index)} B, ${index.split('\n').length} lines)\n`
      + `  → ${rel(LLMS_FULL_PATH)} (${Buffer.byteLength(full)} B, ${full.split('\n').length} lines)`,
    )
  }
}
/* c8 ignore stop */
